alias Tradewinds.Repo
alias Tradewinds.Schema.{Country, Port, Route, Shipyard}

england =
  Repo.insert!(%Country{
    name: "England",
    description: "The home country of the British Empire."
  })

scotland =
  Repo.insert!(%Country{
    name: "Scotland",
    description: "A nation in the United Kingdom."
  })

ireland =
  Repo.insert!(%Country{
    name: "Ireland",
    description: "The Emerald Isle."
  })

netherlands =
  Repo.insert!(%Country{
    name: "Netherlands",
    description: "A low-lying country known for windmills."
  })

belgium =
  Repo.insert!(%Country{
    name: "Belgium",
    description: "Known for its waffles and chocolate."
  })

france =
  Repo.insert!(%Country{
    name: "France",
    description: "A major European power."
  })

spain =
  Repo.insert!(%Country{
    name: "Spain",
    description: "Located on the Iberian Peninsula."
  })

portugal =
  Repo.insert!(%Country{
    name: "Portugal",
    description: "A maritime nation on the Atlantic coast."
  })

italy =
  Repo.insert!(%Country{
    name: "Italy",
    description: "Shaped like a boot, with a rich history."
  })

papal_states =
  Repo.insert!(%Country{
    name: "Papal States",
    description: "The territories under the direct sovereign rule of the Pope."
  })

malta =
  Repo.insert!(%Country{
    name: "Malta",
    description: "An archipelago in the central Mediterranean."
  })

ottoman_empire =
  Repo.insert!(%Country{
    name: "Ottoman Empire",
    description: "A vast empire spanning three continents."
  })

denmark =
  Repo.insert!(%Country{
    name: "Denmark",
    description: "A Scandinavian country."
  })

sweden =
  Repo.insert!(%Country{
    name: "Sweden",
    description: "A Nordic country with vast forests."
  })

norway =
  Repo.insert!(%Country{
    name: "Norway",
    description: "Known for its fjords and mountains."
  })

hanseatic_league =
  Repo.insert!(%Country{
    name: "Hanseatic League",
    description: "A commercial and defensive confederation."
  })

poland =
  Repo.insert!(%Country{
    name: "Poland",
    description: "A country in Central Europe."
  })

russia =
  Repo.insert!(%Country{
    name: "Russia",
    description: "The largest country in the world."
  })

# Insert Ports

lon =
  Repo.insert!(%Port{
    name: "London",
    shortcode: "LON",
    country: england
  })

brs =
  Repo.insert!(%Port{
    name: "Bristol",
    shortcode: "BRS",
    country: england
  })

ply =
  Repo.insert!(%Port{
    name: "Plymouth",
    shortcode: "PLY",
    country: england
  })

liv =
  Repo.insert!(%Port{
    name: "Liverpool",
    shortcode: "LIV",
    country: england
  })

edi =
  Repo.insert!(%Port{
    name: "Leith",
    shortcode: "EDI",
    country: scotland
  })

gla =
  Repo.insert!(%Port{
    name: "Glasgow",
    shortcode: "GLA",
    country: scotland
  })

dub =
  Repo.insert!(%Port{
    name: "Dublin",
    shortcode: "DUB",
    country: ireland
  })

ams =
  Repo.insert!(%Port{
    name: "Amsterdam",
    shortcode: "AMS",
    country: netherlands
  })

rot =
  Repo.insert!(%Port{
    name: "Rotterdam",
    shortcode: "ROT",
    country: netherlands
  })

mid =
  Repo.insert!(%Port{
    name: "Middelburg",
    shortcode: "MID",
    country: netherlands
  })

ant =
  Repo.insert!(%Port{
    name: "Antwerp",
    shortcode: "ANT",
    country: belgium
  })

rou =
  Repo.insert!(%Port{
    name: "Rouen",
    shortcode: "ROU",
    country: france
  })

lro =
  Repo.insert!(%Port{
    name: "La Rochelle",
    shortcode: "LRO",
    country: france
  })

bor =
  Repo.insert!(%Port{
    name: "Bordeaux",
    shortcode: "BOR",
    country: france
  })

mrs =
  Repo.insert!(%Port{
    name: "Marseille",
    shortcode: "MRS",
    country: france
  })

sev =
  Repo.insert!(%Port{
    name: "Seville",
    shortcode: "SEV",
    country: spain
  })

cad =
  Repo.insert!(%Port{
    name: "Cadiz",
    shortcode: "CAD",
    country: spain
  })

bar =
  Repo.insert!(%Port{
    name: "Barcelona",
    shortcode: "BAR",
    country: spain
  })

lis =
  Repo.insert!(%Port{
    name: "Lisbon",
    shortcode: "LIS",
    country: portugal
  })

por =
  Repo.insert!(%Port{
    name: "Porto",
    shortcode: "POR",
    country: portugal
  })

ven =
  Repo.insert!(%Port{
    name: "Venice",
    shortcode: "VEN",
    country: italy
  })

gen =
  Repo.insert!(%Port{
    name: "Genoa",
    shortcode: "GEN",
    country: italy
  })

nap =
  Repo.insert!(%Port{
    name: "Naples",
    shortcode: "NAP",
    country: italy
  })

lvo =
  Repo.insert!(%Port{
    name: "Livorno",
    shortcode: "LVO",
    country: italy
  })

anc =
  Repo.insert!(%Port{
    name: "Ancona",
    shortcode: "ANC",
    country: papal_states
  })

val =
  Repo.insert!(%Port{
    name: "Valletta",
    shortcode: "VAL",
    country: malta
  })

con =
  Repo.insert!(%Port{
    name: "Constantinople",
    shortcode: "CON",
    country: ottoman_empire
  })

smi =
  Repo.insert!(%Port{
    name: "Izmir",
    shortcode: "SMI",
    country: ottoman_empire
  })

sal =
  Repo.insert!(%Port{
    name: "Thessaloniki",
    shortcode: "SAL",
    country: ottoman_empire
  })

cph =
  Repo.insert!(%Port{
    name: "Copenhagen",
    shortcode: "CPH",
    country: denmark
  })

sto =
  Repo.insert!(%Port{
    name: "Stockholm",
    shortcode: "STO",
    country: sweden
  })

ber =
  Repo.insert!(%Port{
    name: "Bergen",
    shortcode: "BER",
    country: norway
  })

ham =
  Repo.insert!(%Port{
    name: "Hamburg",
    shortcode: "HAM",
    country: hanseatic_league
  })

lub =
  Repo.insert!(%Port{
    name: "Lübeck",
    shortcode: "LUB",
    country: hanseatic_league
  })

bre =
  Repo.insert!(%Port{
    name: "Bremen",
    shortcode: "BRE",
    country: hanseatic_league
  })

gdn =
  Repo.insert!(%Port{
    name: "Gdańsk",
    shortcode: "GDN",
    country: poland
  })

arg =
  Repo.insert!(%Port{
    name: "Arkhangelsk",
    shortcode: "ARG",
    country: russia
  })

Repo.insert!(%Route{from_id: lon.id, to_id: brs.id, distance: 198})
Repo.insert!(%Route{from_id: lon.id, to_id: ply.id, distance: 334})
Repo.insert!(%Route{from_id: lon.id, to_id: liv.id, distance: 278})
Repo.insert!(%Route{from_id: lon.id, to_id: edi.id, distance: 445})
Repo.insert!(%Route{from_id: lon.id, to_id: gla.id, distance: 408})
Repo.insert!(%Route{from_id: lon.id, to_id: dub.id, distance: 491})
Repo.insert!(%Route{from_id: lon.id, to_id: ams.id, distance: 220})
Repo.insert!(%Route{from_id: lon.id, to_id: rot.id, distance: 220})
Repo.insert!(%Route{from_id: lon.id, to_id: mid.id, distance: 271})
Repo.insert!(%Route{from_id: lon.id, to_id: ant.id, distance: 399})
Repo.insert!(%Route{from_id: lon.id, to_id: rou.id, distance: 97})
Repo.insert!(%Route{from_id: lon.id, to_id: lro.id, distance: 289})
Repo.insert!(%Route{from_id: lon.id, to_id: bor.id, distance: 414})
Repo.insert!(%Route{from_id: lon.id, to_id: mrs.id, distance: 376})
Repo.insert!(%Route{from_id: lon.id, to_id: sev.id, distance: 870})
Repo.insert!(%Route{from_id: lon.id, to_id: cad.id, distance: 870})
Repo.insert!(%Route{from_id: lon.id, to_id: bar.id, distance: 592})
Repo.insert!(%Route{from_id: lon.id, to_id: lis.id, distance: 1085})
Repo.insert!(%Route{from_id: lon.id, to_id: por.id, distance: 1085})
Repo.insert!(%Route{from_id: lon.id, to_id: ven.id, distance: 1202})
Repo.insert!(%Route{from_id: lon.id, to_id: gen.id, distance: 1293})
Repo.insert!(%Route{from_id: lon.id, to_id: nap.id, distance: 1468})
Repo.insert!(%Route{from_id: lon.id, to_id: lvo.id, distance: 1287})
Repo.insert!(%Route{from_id: lon.id, to_id: anc.id, distance: 1311})
Repo.insert!(%Route{from_id: lon.id, to_id: val.id, distance: 1758})
Repo.insert!(%Route{from_id: lon.id, to_id: con.id, distance: 2436})
Repo.insert!(%Route{from_id: lon.id, to_id: smi.id, distance: 2058})
Repo.insert!(%Route{from_id: lon.id, to_id: sal.id, distance: 1857})
Repo.insert!(%Route{from_id: lon.id, to_id: cph.id, distance: 904})
Repo.insert!(%Route{from_id: lon.id, to_id: sto.id, distance: 1367})
Repo.insert!(%Route{from_id: lon.id, to_id: ber.id, distance: 704})
Repo.insert!(%Route{from_id: lon.id, to_id: ham.id, distance: 740})
Repo.insert!(%Route{from_id: lon.id, to_id: lub.id, distance: 740})
Repo.insert!(%Route{from_id: lon.id, to_id: bre.id, distance: 659})
Repo.insert!(%Route{from_id: lon.id, to_id: gdn.id, distance: 1112})
Repo.insert!(%Route{from_id: lon.id, to_id: arg.id, distance: 5065})
Repo.insert!(%Route{from_id: brs.id, to_id: lon.id, distance: 198})
Repo.insert!(%Route{from_id: brs.id, to_id: ply.id, distance: 405})
Repo.insert!(%Route{from_id: brs.id, to_id: liv.id, distance: 80})
Repo.insert!(%Route{from_id: brs.id, to_id: edi.id, distance: 247})
Repo.insert!(%Route{from_id: brs.id, to_id: gla.id, distance: 210})
Repo.insert!(%Route{from_id: brs.id, to_id: dub.id, distance: 292})
Repo.insert!(%Route{from_id: brs.id, to_id: ams.id, distance: 419})
Repo.insert!(%Route{from_id: brs.id, to_id: rot.id, distance: 419})
Repo.insert!(%Route{from_id: brs.id, to_id: mid.id, distance: 422})
Repo.insert!(%Route{from_id: brs.id, to_id: ant.id, distance: 512})
Repo.insert!(%Route{from_id: brs.id, to_id: rou.id, distance: 210})
Repo.insert!(%Route{from_id: brs.id, to_id: lro.id, distance: 403})
Repo.insert!(%Route{from_id: brs.id, to_id: bor.id, distance: 527})
Repo.insert!(%Route{from_id: brs.id, to_id: mrs.id, distance: 489})
Repo.insert!(%Route{from_id: brs.id, to_id: sev.id, distance: 983})
Repo.insert!(%Route{from_id: brs.id, to_id: cad.id, distance: 983})
Repo.insert!(%Route{from_id: brs.id, to_id: bar.id, distance: 706})
Repo.insert!(%Route{from_id: brs.id, to_id: lis.id, distance: 1155})
Repo.insert!(%Route{from_id: brs.id, to_id: por.id, distance: 1155})
Repo.insert!(%Route{from_id: brs.id, to_id: ven.id, distance: 1400})
Repo.insert!(%Route{from_id: brs.id, to_id: gen.id, distance: 1491})
Repo.insert!(%Route{from_id: brs.id, to_id: nap.id, distance: 1667})
Repo.insert!(%Route{from_id: brs.id, to_id: lvo.id, distance: 1486})
Repo.insert!(%Route{from_id: brs.id, to_id: anc.id, distance: 1509})
Repo.insert!(%Route{from_id: brs.id, to_id: val.id, distance: 1957})
Repo.insert!(%Route{from_id: brs.id, to_id: con.id, distance: 2635})
Repo.insert!(%Route{from_id: brs.id, to_id: smi.id, distance: 2256})
Repo.insert!(%Route{from_id: brs.id, to_id: sal.id, distance: 2055})
Repo.insert!(%Route{from_id: brs.id, to_id: cph.id, distance: 1102})
Repo.insert!(%Route{from_id: brs.id, to_id: sto.id, distance: 1565})
Repo.insert!(%Route{from_id: brs.id, to_id: ber.id, distance: 799})
Repo.insert!(%Route{from_id: brs.id, to_id: ham.id, distance: 939})
Repo.insert!(%Route{from_id: brs.id, to_id: lub.id, distance: 939})
Repo.insert!(%Route{from_id: brs.id, to_id: bre.id, distance: 858})
Repo.insert!(%Route{from_id: brs.id, to_id: gdn.id, distance: 1311})
Repo.insert!(%Route{from_id: brs.id, to_id: arg.id, distance: 5264})
Repo.insert!(%Route{from_id: ply.id, to_id: lon.id, distance: 334})
Repo.insert!(%Route{from_id: ply.id, to_id: brs.id, distance: 405})
Repo.insert!(%Route{from_id: ply.id, to_id: liv.id, distance: 485})
Repo.insert!(%Route{from_id: ply.id, to_id: edi.id, distance: 652})
Repo.insert!(%Route{from_id: ply.id, to_id: gla.id, distance: 615})
Repo.insert!(%Route{from_id: ply.id, to_id: dub.id, distance: 573})
Repo.insert!(%Route{from_id: ply.id, to_id: ams.id, distance: 555})
Repo.insert!(%Route{from_id: ply.id, to_id: rot.id, distance: 555})
Repo.insert!(%Route{from_id: ply.id, to_id: mid.id, distance: 511})
Repo.insert!(%Route{from_id: ply.id, to_id: ant.id, distance: 602})
Repo.insert!(%Route{from_id: ply.id, to_id: rou.id, distance: 300})
Repo.insert!(%Route{from_id: ply.id, to_id: lro.id, distance: 492})
Repo.insert!(%Route{from_id: ply.id, to_id: bor.id, distance: 617})
Repo.insert!(%Route{from_id: ply.id, to_id: mrs.id, distance: 579})
Repo.insert!(%Route{from_id: ply.id, to_id: sev.id, distance: 930})
Repo.insert!(%Route{from_id: ply.id, to_id: cad.id, distance: 930})
Repo.insert!(%Route{from_id: ply.id, to_id: bar.id, distance: 795})
Repo.insert!(%Route{from_id: ply.id, to_id: lis.id, distance: 898})
Repo.insert!(%Route{from_id: ply.id, to_id: por.id, distance: 898})
Repo.insert!(%Route{from_id: ply.id, to_id: ven.id, distance: 1504})
Repo.insert!(%Route{from_id: ply.id, to_id: gen.id, distance: 1595})
Repo.insert!(%Route{from_id: ply.id, to_id: nap.id, distance: 1771})
Repo.insert!(%Route{from_id: ply.id, to_id: lvo.id, distance: 1590})
Repo.insert!(%Route{from_id: ply.id, to_id: anc.id, distance: 1613})
Repo.insert!(%Route{from_id: ply.id, to_id: val.id, distance: 2061})
Repo.insert!(%Route{from_id: ply.id, to_id: con.id, distance: 2739})
Repo.insert!(%Route{from_id: ply.id, to_id: smi.id, distance: 2360})
Repo.insert!(%Route{from_id: ply.id, to_id: sal.id, distance: 2159})
Repo.insert!(%Route{from_id: ply.id, to_id: cph.id, distance: 1207})
Repo.insert!(%Route{from_id: ply.id, to_id: sto.id, distance: 1670})
Repo.insert!(%Route{from_id: ply.id, to_id: ber.id, distance: 1039})
Repo.insert!(%Route{from_id: ply.id, to_id: ham.id, distance: 1075})
Repo.insert!(%Route{from_id: ply.id, to_id: lub.id, distance: 1075})
Repo.insert!(%Route{from_id: ply.id, to_id: bre.id, distance: 994})
Repo.insert!(%Route{from_id: ply.id, to_id: gdn.id, distance: 1415})
Repo.insert!(%Route{from_id: ply.id, to_id: arg.id, distance: 5368})
Repo.insert!(%Route{from_id: liv.id, to_id: lon.id, distance: 278})
Repo.insert!(%Route{from_id: liv.id, to_id: brs.id, distance: 80})
Repo.insert!(%Route{from_id: liv.id, to_id: ply.id, distance: 485})
Repo.insert!(%Route{from_id: liv.id, to_id: edi.id, distance: 167})
Repo.insert!(%Route{from_id: liv.id, to_id: gla.id, distance: 130})
Repo.insert!(%Route{from_id: liv.id, to_id: dub.id, distance: 212})
Repo.insert!(%Route{from_id: liv.id, to_id: ams.id, distance: 379})
Repo.insert!(%Route{from_id: liv.id, to_id: rot.id, distance: 379})
Repo.insert!(%Route{from_id: liv.id, to_id: mid.id, distance: 430})
Repo.insert!(%Route{from_id: liv.id, to_id: ant.id, distance: 592})
Repo.insert!(%Route{from_id: liv.id, to_id: rou.id, distance: 290})
Repo.insert!(%Route{from_id: liv.id, to_id: lro.id, distance: 483})
Repo.insert!(%Route{from_id: liv.id, to_id: bor.id, distance: 607})
Repo.insert!(%Route{from_id: liv.id, to_id: mrs.id, distance: 569})
Repo.insert!(%Route{from_id: liv.id, to_id: sev.id, distance: 1064})
Repo.insert!(%Route{from_id: liv.id, to_id: cad.id, distance: 1064})
Repo.insert!(%Route{from_id: liv.id, to_id: bar.id, distance: 786})
Repo.insert!(%Route{from_id: liv.id, to_id: lis.id, distance: 1084})
Repo.insert!(%Route{from_id: liv.id, to_id: por.id, distance: 1084})
Repo.insert!(%Route{from_id: liv.id, to_id: ven.id, distance: 1360})
Repo.insert!(%Route{from_id: liv.id, to_id: gen.id, distance: 1451})
Repo.insert!(%Route{from_id: liv.id, to_id: nap.id, distance: 1627})
Repo.insert!(%Route{from_id: liv.id, to_id: lvo.id, distance: 1446})
Repo.insert!(%Route{from_id: liv.id, to_id: anc.id, distance: 1470})
Repo.insert!(%Route{from_id: liv.id, to_id: val.id, distance: 1917})
Repo.insert!(%Route{from_id: liv.id, to_id: con.id, distance: 2595})
Repo.insert!(%Route{from_id: liv.id, to_id: smi.id, distance: 2216})
Repo.insert!(%Route{from_id: liv.id, to_id: sal.id, distance: 2015})
Repo.insert!(%Route{from_id: liv.id, to_id: cph.id, distance: 1063})
Repo.insert!(%Route{from_id: liv.id, to_id: sto.id, distance: 1526})
Repo.insert!(%Route{from_id: liv.id, to_id: ber.id, distance: 719})
Repo.insert!(%Route{from_id: liv.id, to_id: ham.id, distance: 899})
Repo.insert!(%Route{from_id: liv.id, to_id: lub.id, distance: 899})
Repo.insert!(%Route{from_id: liv.id, to_id: bre.id, distance: 818})
Repo.insert!(%Route{from_id: liv.id, to_id: gdn.id, distance: 1271})
Repo.insert!(%Route{from_id: liv.id, to_id: arg.id, distance: 5224})
Repo.insert!(%Route{from_id: edi.id, to_id: lon.id, distance: 445})
Repo.insert!(%Route{from_id: edi.id, to_id: brs.id, distance: 247})
Repo.insert!(%Route{from_id: edi.id, to_id: ply.id, distance: 652})
Repo.insert!(%Route{from_id: edi.id, to_id: liv.id, distance: 167})
Repo.insert!(%Route{from_id: edi.id, to_id: gla.id, distance: 151})
Repo.insert!(%Route{from_id: edi.id, to_id: dub.id, distance: 273})
Repo.insert!(%Route{from_id: edi.id, to_id: ams.id, distance: 546})
Repo.insert!(%Route{from_id: edi.id, to_id: rot.id, distance: 546})
Repo.insert!(%Route{from_id: edi.id, to_id: mid.id, distance: 597})
Repo.insert!(%Route{from_id: edi.id, to_id: ant.id, distance: 760})
Repo.insert!(%Route{from_id: edi.id, to_id: rou.id, distance: 457})
Repo.insert!(%Route{from_id: edi.id, to_id: lro.id, distance: 650})
Repo.insert!(%Route{from_id: edi.id, to_id: bor.id, distance: 774})
Repo.insert!(%Route{from_id: edi.id, to_id: mrs.id, distance: 736})
Repo.insert!(%Route{from_id: edi.id, to_id: sev.id, distance: 1177})
Repo.insert!(%Route{from_id: edi.id, to_id: cad.id, distance: 1177})
Repo.insert!(%Route{from_id: edi.id, to_id: bar.id, distance: 953})
Repo.insert!(%Route{from_id: edi.id, to_id: lis.id, distance: 1145})
Repo.insert!(%Route{from_id: edi.id, to_id: por.id, distance: 1145})
Repo.insert!(%Route{from_id: edi.id, to_id: ven.id, distance: 1518})
Repo.insert!(%Route{from_id: edi.id, to_id: gen.id, distance: 1609})
Repo.insert!(%Route{from_id: edi.id, to_id: nap.id, distance: 1784})
Repo.insert!(%Route{from_id: edi.id, to_id: lvo.id, distance: 1604})
Repo.insert!(%Route{from_id: edi.id, to_id: anc.id, distance: 1627})
Repo.insert!(%Route{from_id: edi.id, to_id: val.id, distance: 2074})
Repo.insert!(%Route{from_id: edi.id, to_id: con.id, distance: 2753})
Repo.insert!(%Route{from_id: edi.id, to_id: smi.id, distance: 2374})
Repo.insert!(%Route{from_id: edi.id, to_id: sal.id, distance: 2173})
Repo.insert!(%Route{from_id: edi.id, to_id: cph.id, distance: 1220})
Repo.insert!(%Route{from_id: edi.id, to_id: sto.id, distance: 1456})
Repo.insert!(%Route{from_id: edi.id, to_id: ber.id, distance: 552})
Repo.insert!(%Route{from_id: edi.id, to_id: ham.id, distance: 914})
Repo.insert!(%Route{from_id: edi.id, to_id: lub.id, distance: 914})
Repo.insert!(%Route{from_id: edi.id, to_id: bre.id, distance: 833})
Repo.insert!(%Route{from_id: edi.id, to_id: gdn.id, distance: 1428})
Repo.insert!(%Route{from_id: edi.id, to_id: arg.id, distance: 5381})
Repo.insert!(%Route{from_id: gla.id, to_id: lon.id, distance: 408})
Repo.insert!(%Route{from_id: gla.id, to_id: brs.id, distance: 210})
Repo.insert!(%Route{from_id: gla.id, to_id: ply.id, distance: 615})
Repo.insert!(%Route{from_id: gla.id, to_id: liv.id, distance: 130})
Repo.insert!(%Route{from_id: gla.id, to_id: edi.id, distance: 151})
Repo.insert!(%Route{from_id: gla.id, to_id: dub.id, distance: 236})
Repo.insert!(%Route{from_id: gla.id, to_id: ams.id, distance: 509})
Repo.insert!(%Route{from_id: gla.id, to_id: rot.id, distance: 509})
Repo.insert!(%Route{from_id: gla.id, to_id: mid.id, distance: 561})
Repo.insert!(%Route{from_id: gla.id, to_id: ant.id, distance: 723})
Repo.insert!(%Route{from_id: gla.id, to_id: rou.id, distance: 421})
Repo.insert!(%Route{from_id: gla.id, to_id: lro.id, distance: 613})
Repo.insert!(%Route{from_id: gla.id, to_id: bor.id, distance: 738})
Repo.insert!(%Route{from_id: gla.id, to_id: mrs.id, distance: 700})
Repo.insert!(%Route{from_id: gla.id, to_id: sev.id, distance: 1082})
Repo.insert!(%Route{from_id: gla.id, to_id: cad.id, distance: 1082})
Repo.insert!(%Route{from_id: gla.id, to_id: bar.id, distance: 916})
Repo.insert!(%Route{from_id: gla.id, to_id: lis.id, distance: 1050})
Repo.insert!(%Route{from_id: gla.id, to_id: por.id, distance: 1050})
Repo.insert!(%Route{from_id: gla.id, to_id: ven.id, distance: 1491})
Repo.insert!(%Route{from_id: gla.id, to_id: gen.id, distance: 1582})
Repo.insert!(%Route{from_id: gla.id, to_id: nap.id, distance: 1758})
Repo.insert!(%Route{from_id: gla.id, to_id: lvo.id, distance: 1577})
Repo.insert!(%Route{from_id: gla.id, to_id: anc.id, distance: 1600})
Repo.insert!(%Route{from_id: gla.id, to_id: val.id, distance: 2048})
Repo.insert!(%Route{from_id: gla.id, to_id: con.id, distance: 2726})
Repo.insert!(%Route{from_id: gla.id, to_id: smi.id, distance: 2347})
Repo.insert!(%Route{from_id: gla.id, to_id: sal.id, distance: 2146})
Repo.insert!(%Route{from_id: gla.id, to_id: cph.id, distance: 1193})
Repo.insert!(%Route{from_id: gla.id, to_id: sto.id, distance: 1598})
Repo.insert!(%Route{from_id: gla.id, to_id: ber.id, distance: 694})
Repo.insert!(%Route{from_id: gla.id, to_id: ham.id, distance: 1030})
Repo.insert!(%Route{from_id: gla.id, to_id: lub.id, distance: 1030})
Repo.insert!(%Route{from_id: gla.id, to_id: bre.id, distance: 949})
Repo.insert!(%Route{from_id: gla.id, to_id: gdn.id, distance: 1402})
Repo.insert!(%Route{from_id: gla.id, to_id: arg.id, distance: 5355})
Repo.insert!(%Route{from_id: dub.id, to_id: lon.id, distance: 491})
Repo.insert!(%Route{from_id: dub.id, to_id: brs.id, distance: 292})
Repo.insert!(%Route{from_id: dub.id, to_id: ply.id, distance: 573})
Repo.insert!(%Route{from_id: dub.id, to_id: liv.id, distance: 212})
Repo.insert!(%Route{from_id: dub.id, to_id: edi.id, distance: 273})
Repo.insert!(%Route{from_id: dub.id, to_id: gla.id, distance: 236})
Repo.insert!(%Route{from_id: dub.id, to_id: ams.id, distance: 592})
Repo.insert!(%Route{from_id: dub.id, to_id: rot.id, distance: 592})
Repo.insert!(%Route{from_id: dub.id, to_id: mid.id, distance: 643})
Repo.insert!(%Route{from_id: dub.id, to_id: ant.id, distance: 805})
Repo.insert!(%Route{from_id: dub.id, to_id: rou.id, distance: 503})
Repo.insert!(%Route{from_id: dub.id, to_id: lro.id, distance: 696})
Repo.insert!(%Route{from_id: dub.id, to_id: bor.id, distance: 820})
Repo.insert!(%Route{from_id: dub.id, to_id: mrs.id, distance: 782})
Repo.insert!(%Route{from_id: dub.id, to_id: sev.id, distance: 903})
Repo.insert!(%Route{from_id: dub.id, to_id: cad.id, distance: 903})
Repo.insert!(%Route{from_id: dub.id, to_id: bar.id, distance: 999})
Repo.insert!(%Route{from_id: dub.id, to_id: lis.id, distance: 871})
Repo.insert!(%Route{from_id: dub.id, to_id: por.id, distance: 871})
Repo.insert!(%Route{from_id: dub.id, to_id: ven.id, distance: 1573})
Repo.insert!(%Route{from_id: dub.id, to_id: gen.id, distance: 1664})
Repo.insert!(%Route{from_id: dub.id, to_id: nap.id, distance: 1840})
Repo.insert!(%Route{from_id: dub.id, to_id: lvo.id, distance: 1659})
Repo.insert!(%Route{from_id: dub.id, to_id: anc.id, distance: 1682})
Repo.insert!(%Route{from_id: dub.id, to_id: val.id, distance: 2130})
Repo.insert!(%Route{from_id: dub.id, to_id: con.id, distance: 2808})
Repo.insert!(%Route{from_id: dub.id, to_id: smi.id, distance: 2429})
Repo.insert!(%Route{from_id: dub.id, to_id: sal.id, distance: 2228})
Repo.insert!(%Route{from_id: dub.id, to_id: cph.id, distance: 1276})
Repo.insert!(%Route{from_id: dub.id, to_id: sto.id, distance: 1729})
Repo.insert!(%Route{from_id: dub.id, to_id: ber.id, distance: 826})
Repo.insert!(%Route{from_id: dub.id, to_id: ham.id, distance: 1112})
Repo.insert!(%Route{from_id: dub.id, to_id: lub.id, distance: 1112})
Repo.insert!(%Route{from_id: dub.id, to_id: bre.id, distance: 1031})
Repo.insert!(%Route{from_id: dub.id, to_id: gdn.id, distance: 1484})
Repo.insert!(%Route{from_id: dub.id, to_id: arg.id, distance: 5437})
Repo.insert!(%Route{from_id: ams.id, to_id: lon.id, distance: 220})
Repo.insert!(%Route{from_id: ams.id, to_id: brs.id, distance: 419})
Repo.insert!(%Route{from_id: ams.id, to_id: ply.id, distance: 555})
Repo.insert!(%Route{from_id: ams.id, to_id: liv.id, distance: 379})
Repo.insert!(%Route{from_id: ams.id, to_id: edi.id, distance: 546})
Repo.insert!(%Route{from_id: ams.id, to_id: gla.id, distance: 509})
Repo.insert!(%Route{from_id: ams.id, to_id: dub.id, distance: 592})
Repo.insert!(%Route{from_id: ams.id, to_id: mid.id, distance: 51})
Repo.insert!(%Route{from_id: ams.id, to_id: ant.id, distance: 565})
Repo.insert!(%Route{from_id: ams.id, to_id: rou.id, distance: 263})
Repo.insert!(%Route{from_id: ams.id, to_id: lro.id, distance: 455})
Repo.insert!(%Route{from_id: ams.id, to_id: bor.id, distance: 580})
Repo.insert!(%Route{from_id: ams.id, to_id: mrs.id, distance: 542})
Repo.insert!(%Route{from_id: ams.id, to_id: sev.id, distance: 1036})
Repo.insert!(%Route{from_id: ams.id, to_id: cad.id, distance: 1036})
Repo.insert!(%Route{from_id: ams.id, to_id: bar.id, distance: 758})
Repo.insert!(%Route{from_id: ams.id, to_id: lis.id, distance: 1254})
Repo.insert!(%Route{from_id: ams.id, to_id: por.id, distance: 1254})
Repo.insert!(%Route{from_id: ams.id, to_id: ven.id, distance: 981})
Repo.insert!(%Route{from_id: ams.id, to_id: gen.id, distance: 1072})
Repo.insert!(%Route{from_id: ams.id, to_id: nap.id, distance: 1248})
Repo.insert!(%Route{from_id: ams.id, to_id: lvo.id, distance: 1067})
Repo.insert!(%Route{from_id: ams.id, to_id: anc.id, distance: 1090})
Repo.insert!(%Route{from_id: ams.id, to_id: val.id, distance: 1538})
Repo.insert!(%Route{from_id: ams.id, to_id: con.id, distance: 2216})
Repo.insert!(%Route{from_id: ams.id, to_id: smi.id, distance: 1837})
Repo.insert!(%Route{from_id: ams.id, to_id: sal.id, distance: 1636})
Repo.insert!(%Route{from_id: ams.id, to_id: cph.id, distance: 683})
Repo.insert!(%Route{from_id: ams.id, to_id: sto.id, distance: 1146})
Repo.insert!(%Route{from_id: ams.id, to_id: ber.id, distance: 609})
Repo.insert!(%Route{from_id: ams.id, to_id: ham.id, distance: 527})
Repo.insert!(%Route{from_id: ams.id, to_id: lub.id, distance: 527})
Repo.insert!(%Route{from_id: ams.id, to_id: bre.id, distance: 446})
Repo.insert!(%Route{from_id: ams.id, to_id: gdn.id, distance: 892})
Repo.insert!(%Route{from_id: ams.id, to_id: arg.id, distance: 4845})
Repo.insert!(%Route{from_id: rot.id, to_id: lon.id, distance: 220})
Repo.insert!(%Route{from_id: rot.id, to_id: brs.id, distance: 419})
Repo.insert!(%Route{from_id: rot.id, to_id: ply.id, distance: 555})
Repo.insert!(%Route{from_id: rot.id, to_id: liv.id, distance: 379})
Repo.insert!(%Route{from_id: rot.id, to_id: edi.id, distance: 546})
Repo.insert!(%Route{from_id: rot.id, to_id: gla.id, distance: 509})
Repo.insert!(%Route{from_id: rot.id, to_id: dub.id, distance: 592})
Repo.insert!(%Route{from_id: rot.id, to_id: mid.id, distance: 51})
Repo.insert!(%Route{from_id: rot.id, to_id: ant.id, distance: 565})
Repo.insert!(%Route{from_id: rot.id, to_id: rou.id, distance: 263})
Repo.insert!(%Route{from_id: rot.id, to_id: lro.id, distance: 455})
Repo.insert!(%Route{from_id: rot.id, to_id: bor.id, distance: 580})
Repo.insert!(%Route{from_id: rot.id, to_id: mrs.id, distance: 542})
Repo.insert!(%Route{from_id: rot.id, to_id: sev.id, distance: 1036})
Repo.insert!(%Route{from_id: rot.id, to_id: cad.id, distance: 1036})
Repo.insert!(%Route{from_id: rot.id, to_id: bar.id, distance: 758})
Repo.insert!(%Route{from_id: rot.id, to_id: lis.id, distance: 1254})
Repo.insert!(%Route{from_id: rot.id, to_id: por.id, distance: 1254})
Repo.insert!(%Route{from_id: rot.id, to_id: ven.id, distance: 981})
Repo.insert!(%Route{from_id: rot.id, to_id: gen.id, distance: 1072})
Repo.insert!(%Route{from_id: rot.id, to_id: nap.id, distance: 1248})
Repo.insert!(%Route{from_id: rot.id, to_id: lvo.id, distance: 1067})
Repo.insert!(%Route{from_id: rot.id, to_id: anc.id, distance: 1090})
Repo.insert!(%Route{from_id: rot.id, to_id: val.id, distance: 1538})
Repo.insert!(%Route{from_id: rot.id, to_id: con.id, distance: 2216})
Repo.insert!(%Route{from_id: rot.id, to_id: smi.id, distance: 1837})
Repo.insert!(%Route{from_id: rot.id, to_id: sal.id, distance: 1636})
Repo.insert!(%Route{from_id: rot.id, to_id: cph.id, distance: 683})
Repo.insert!(%Route{from_id: rot.id, to_id: sto.id, distance: 1146})
Repo.insert!(%Route{from_id: rot.id, to_id: ber.id, distance: 609})
Repo.insert!(%Route{from_id: rot.id, to_id: ham.id, distance: 527})
Repo.insert!(%Route{from_id: rot.id, to_id: lub.id, distance: 527})
Repo.insert!(%Route{from_id: rot.id, to_id: bre.id, distance: 446})
Repo.insert!(%Route{from_id: rot.id, to_id: gdn.id, distance: 892})
Repo.insert!(%Route{from_id: rot.id, to_id: arg.id, distance: 4845})
Repo.insert!(%Route{from_id: mid.id, to_id: lon.id, distance: 271})
Repo.insert!(%Route{from_id: mid.id, to_id: brs.id, distance: 422})
Repo.insert!(%Route{from_id: mid.id, to_id: ply.id, distance: 511})
Repo.insert!(%Route{from_id: mid.id, to_id: liv.id, distance: 430})
Repo.insert!(%Route{from_id: mid.id, to_id: edi.id, distance: 597})
Repo.insert!(%Route{from_id: mid.id, to_id: gla.id, distance: 561})
Repo.insert!(%Route{from_id: mid.id, to_id: dub.id, distance: 643})
Repo.insert!(%Route{from_id: mid.id, to_id: ams.id, distance: 51})
Repo.insert!(%Route{from_id: mid.id, to_id: rot.id, distance: 51})
Repo.insert!(%Route{from_id: mid.id, to_id: ant.id, distance: 514})
Repo.insert!(%Route{from_id: mid.id, to_id: rou.id, distance: 211})
Repo.insert!(%Route{from_id: mid.id, to_id: lro.id, distance: 404})
Repo.insert!(%Route{from_id: mid.id, to_id: bor.id, distance: 528})
Repo.insert!(%Route{from_id: mid.id, to_id: mrs.id, distance: 490})
Repo.insert!(%Route{from_id: mid.id, to_id: sev.id, distance: 985})
Repo.insert!(%Route{from_id: mid.id, to_id: cad.id, distance: 985})
Repo.insert!(%Route{from_id: mid.id, to_id: bar.id, distance: 707})
Repo.insert!(%Route{from_id: mid.id, to_id: lis.id, distance: 1203})
Repo.insert!(%Route{from_id: mid.id, to_id: por.id, distance: 1203})
Repo.insert!(%Route{from_id: mid.id, to_id: ven.id, distance: 1032})
Repo.insert!(%Route{from_id: mid.id, to_id: gen.id, distance: 1123})
Repo.insert!(%Route{from_id: mid.id, to_id: nap.id, distance: 1299})
Repo.insert!(%Route{from_id: mid.id, to_id: lvo.id, distance: 1118})
Repo.insert!(%Route{from_id: mid.id, to_id: anc.id, distance: 1141})
Repo.insert!(%Route{from_id: mid.id, to_id: val.id, distance: 1589})
Repo.insert!(%Route{from_id: mid.id, to_id: con.id, distance: 2267})
Repo.insert!(%Route{from_id: mid.id, to_id: smi.id, distance: 1888})
Repo.insert!(%Route{from_id: mid.id, to_id: sal.id, distance: 1687})
Repo.insert!(%Route{from_id: mid.id, to_id: cph.id, distance: 735})
Repo.insert!(%Route{from_id: mid.id, to_id: sto.id, distance: 1198})
Repo.insert!(%Route{from_id: mid.id, to_id: ber.id, distance: 660})
Repo.insert!(%Route{from_id: mid.id, to_id: ham.id, distance: 578})
Repo.insert!(%Route{from_id: mid.id, to_id: lub.id, distance: 578})
Repo.insert!(%Route{from_id: mid.id, to_id: bre.id, distance: 497})
Repo.insert!(%Route{from_id: mid.id, to_id: gdn.id, distance: 943})
Repo.insert!(%Route{from_id: mid.id, to_id: arg.id, distance: 4896})
Repo.insert!(%Route{from_id: ant.id, to_id: lon.id, distance: 399})
Repo.insert!(%Route{from_id: ant.id, to_id: brs.id, distance: 512})
Repo.insert!(%Route{from_id: ant.id, to_id: ply.id, distance: 602})
Repo.insert!(%Route{from_id: ant.id, to_id: liv.id, distance: 592})
Repo.insert!(%Route{from_id: ant.id, to_id: edi.id, distance: 760})
Repo.insert!(%Route{from_id: ant.id, to_id: gla.id, distance: 723})
Repo.insert!(%Route{from_id: ant.id, to_id: dub.id, distance: 805})
Repo.insert!(%Route{from_id: ant.id, to_id: ams.id, distance: 565})
Repo.insert!(%Route{from_id: ant.id, to_id: rot.id, distance: 565})
Repo.insert!(%Route{from_id: ant.id, to_id: mid.id, distance: 514})
Repo.insert!(%Route{from_id: ant.id, to_id: rou.id, distance: 302})
Repo.insert!(%Route{from_id: ant.id, to_id: lro.id, distance: 402})
Repo.insert!(%Route{from_id: ant.id, to_id: bor.id, distance: 526})
Repo.insert!(%Route{from_id: ant.id, to_id: mrs.id, distance: 309})
Repo.insert!(%Route{from_id: ant.id, to_id: sev.id, distance: 916})
Repo.insert!(%Route{from_id: ant.id, to_id: cad.id, distance: 916})
Repo.insert!(%Route{from_id: ant.id, to_id: bar.id, distance: 526})
Repo.insert!(%Route{from_id: ant.id, to_id: lis.id, distance: 1135})
Repo.insert!(%Route{from_id: ant.id, to_id: por.id, distance: 1135})
Repo.insert!(%Route{from_id: ant.id, to_id: ven.id, distance: 902})
Repo.insert!(%Route{from_id: ant.id, to_id: gen.id, distance: 993})
Repo.insert!(%Route{from_id: ant.id, to_id: nap.id, distance: 1168})
Repo.insert!(%Route{from_id: ant.id, to_id: lvo.id, distance: 988})
Repo.insert!(%Route{from_id: ant.id, to_id: anc.id, distance: 1011})
Repo.insert!(%Route{from_id: ant.id, to_id: val.id, distance: 1459})
Repo.insert!(%Route{from_id: ant.id, to_id: con.id, distance: 2137})
Repo.insert!(%Route{from_id: ant.id, to_id: smi.id, distance: 1758})
Repo.insert!(%Route{from_id: ant.id, to_id: sal.id, distance: 1557})
Repo.insert!(%Route{from_id: ant.id, to_id: cph.id, distance: 604})
Repo.insert!(%Route{from_id: ant.id, to_id: sto.id, distance: 1067})
Repo.insert!(%Route{from_id: ant.id, to_id: ber.id, distance: 1087})
Repo.insert!(%Route{from_id: ant.id, to_id: ham.id, distance: 638})
Repo.insert!(%Route{from_id: ant.id, to_id: lub.id, distance: 638})
Repo.insert!(%Route{from_id: ant.id, to_id: bre.id, distance: 646})
Repo.insert!(%Route{from_id: ant.id, to_id: gdn.id, distance: 812})
Repo.insert!(%Route{from_id: ant.id, to_id: arg.id, distance: 4765})
Repo.insert!(%Route{from_id: rou.id, to_id: lon.id, distance: 97})
Repo.insert!(%Route{from_id: rou.id, to_id: brs.id, distance: 210})
Repo.insert!(%Route{from_id: rou.id, to_id: ply.id, distance: 300})
Repo.insert!(%Route{from_id: rou.id, to_id: liv.id, distance: 290})
Repo.insert!(%Route{from_id: rou.id, to_id: edi.id, distance: 457})
Repo.insert!(%Route{from_id: rou.id, to_id: gla.id, distance: 421})
Repo.insert!(%Route{from_id: rou.id, to_id: dub.id, distance: 503})
Repo.insert!(%Route{from_id: rou.id, to_id: ams.id, distance: 263})
Repo.insert!(%Route{from_id: rou.id, to_id: rot.id, distance: 263})
Repo.insert!(%Route{from_id: rou.id, to_id: mid.id, distance: 211})
Repo.insert!(%Route{from_id: rou.id, to_id: ant.id, distance: 302})
Repo.insert!(%Route{from_id: rou.id, to_id: lro.id, distance: 192})
Repo.insert!(%Route{from_id: rou.id, to_id: bor.id, distance: 317})
Repo.insert!(%Route{from_id: rou.id, to_id: mrs.id, distance: 279})
Repo.insert!(%Route{from_id: rou.id, to_id: sev.id, distance: 773})
Repo.insert!(%Route{from_id: rou.id, to_id: cad.id, distance: 773})
Repo.insert!(%Route{from_id: rou.id, to_id: bar.id, distance: 495})
Repo.insert!(%Route{from_id: rou.id, to_id: lis.id, distance: 991})
Repo.insert!(%Route{from_id: rou.id, to_id: por.id, distance: 991})
Repo.insert!(%Route{from_id: rou.id, to_id: ven.id, distance: 1204})
Repo.insert!(%Route{from_id: rou.id, to_id: gen.id, distance: 1295})
Repo.insert!(%Route{from_id: rou.id, to_id: nap.id, distance: 1471})
Repo.insert!(%Route{from_id: rou.id, to_id: lvo.id, distance: 1290})
Repo.insert!(%Route{from_id: rou.id, to_id: anc.id, distance: 1313})
Repo.insert!(%Route{from_id: rou.id, to_id: val.id, distance: 1761})
Repo.insert!(%Route{from_id: rou.id, to_id: con.id, distance: 2439})
Repo.insert!(%Route{from_id: rou.id, to_id: smi.id, distance: 2060})
Repo.insert!(%Route{from_id: rou.id, to_id: sal.id, distance: 1859})
Repo.insert!(%Route{from_id: rou.id, to_id: cph.id, distance: 906})
Repo.insert!(%Route{from_id: rou.id, to_id: sto.id, distance: 1369})
Repo.insert!(%Route{from_id: rou.id, to_id: ber.id, distance: 802})
Repo.insert!(%Route{from_id: rou.id, to_id: ham.id, distance: 790})
Repo.insert!(%Route{from_id: rou.id, to_id: lub.id, distance: 790})
Repo.insert!(%Route{from_id: rou.id, to_id: bre.id, distance: 709})
Repo.insert!(%Route{from_id: rou.id, to_id: gdn.id, distance: 1115})
Repo.insert!(%Route{from_id: rou.id, to_id: arg.id, distance: 5068})
Repo.insert!(%Route{from_id: lro.id, to_id: lon.id, distance: 289})
Repo.insert!(%Route{from_id: lro.id, to_id: brs.id, distance: 403})
Repo.insert!(%Route{from_id: lro.id, to_id: ply.id, distance: 492})
Repo.insert!(%Route{from_id: lro.id, to_id: liv.id, distance: 483})
Repo.insert!(%Route{from_id: lro.id, to_id: edi.id, distance: 650})
Repo.insert!(%Route{from_id: lro.id, to_id: gla.id, distance: 613})
Repo.insert!(%Route{from_id: lro.id, to_id: dub.id, distance: 696})
Repo.insert!(%Route{from_id: lro.id, to_id: ams.id, distance: 455})
Repo.insert!(%Route{from_id: lro.id, to_id: rot.id, distance: 455})
Repo.insert!(%Route{from_id: lro.id, to_id: mid.id, distance: 404})
Repo.insert!(%Route{from_id: lro.id, to_id: ant.id, distance: 402})
Repo.insert!(%Route{from_id: lro.id, to_id: rou.id, distance: 192})
Repo.insert!(%Route{from_id: lro.id, to_id: bor.id, distance: 124})
Repo.insert!(%Route{from_id: lro.id, to_id: mrs.id, distance: 270})
Repo.insert!(%Route{from_id: lro.id, to_id: sev.id, distance: 580})
Repo.insert!(%Route{from_id: lro.id, to_id: cad.id, distance: 580})
Repo.insert!(%Route{from_id: lro.id, to_id: bar.id, distance: 486})
Repo.insert!(%Route{from_id: lro.id, to_id: lis.id, distance: 799})
Repo.insert!(%Route{from_id: lro.id, to_id: por.id, distance: 799})
Repo.insert!(%Route{from_id: lro.id, to_id: ven.id, distance: 1304})
Repo.insert!(%Route{from_id: lro.id, to_id: gen.id, distance: 1395})
Repo.insert!(%Route{from_id: lro.id, to_id: nap.id, distance: 1571})
Repo.insert!(%Route{from_id: lro.id, to_id: lvo.id, distance: 1390})
Repo.insert!(%Route{from_id: lro.id, to_id: anc.id, distance: 1413})
Repo.insert!(%Route{from_id: lro.id, to_id: val.id, distance: 1861})
Repo.insert!(%Route{from_id: lro.id, to_id: con.id, distance: 2539})
Repo.insert!(%Route{from_id: lro.id, to_id: smi.id, distance: 2160})
Repo.insert!(%Route{from_id: lro.id, to_id: sal.id, distance: 1959})
Repo.insert!(%Route{from_id: lro.id, to_id: cph.id, distance: 1006})
Repo.insert!(%Route{from_id: lro.id, to_id: sto.id, distance: 1469})
Repo.insert!(%Route{from_id: lro.id, to_id: ber.id, distance: 994})
Repo.insert!(%Route{from_id: lro.id, to_id: ham.id, distance: 982})
Repo.insert!(%Route{from_id: lro.id, to_id: lub.id, distance: 982})
Repo.insert!(%Route{from_id: lro.id, to_id: bre.id, distance: 902})
Repo.insert!(%Route{from_id: lro.id, to_id: gdn.id, distance: 1215})
Repo.insert!(%Route{from_id: lro.id, to_id: arg.id, distance: 5168})
Repo.insert!(%Route{from_id: bor.id, to_id: lon.id, distance: 414})
Repo.insert!(%Route{from_id: bor.id, to_id: brs.id, distance: 527})
Repo.insert!(%Route{from_id: bor.id, to_id: ply.id, distance: 617})
Repo.insert!(%Route{from_id: bor.id, to_id: liv.id, distance: 607})
Repo.insert!(%Route{from_id: bor.id, to_id: edi.id, distance: 774})
Repo.insert!(%Route{from_id: bor.id, to_id: gla.id, distance: 738})
Repo.insert!(%Route{from_id: bor.id, to_id: dub.id, distance: 820})
Repo.insert!(%Route{from_id: bor.id, to_id: ams.id, distance: 580})
Repo.insert!(%Route{from_id: bor.id, to_id: rot.id, distance: 580})
Repo.insert!(%Route{from_id: bor.id, to_id: mid.id, distance: 528})
Repo.insert!(%Route{from_id: bor.id, to_id: ant.id, distance: 526})
Repo.insert!(%Route{from_id: bor.id, to_id: rou.id, distance: 317})
Repo.insert!(%Route{from_id: bor.id, to_id: lro.id, distance: 124})
Repo.insert!(%Route{from_id: bor.id, to_id: mrs.id, distance: 394})
Repo.insert!(%Route{from_id: bor.id, to_id: sev.id, distance: 456})
Repo.insert!(%Route{from_id: bor.id, to_id: cad.id, distance: 456})
Repo.insert!(%Route{from_id: bor.id, to_id: bar.id, distance: 568})
Repo.insert!(%Route{from_id: bor.id, to_id: lis.id, distance: 674})
Repo.insert!(%Route{from_id: bor.id, to_id: por.id, distance: 674})
Repo.insert!(%Route{from_id: bor.id, to_id: ven.id, distance: 1429})
Repo.insert!(%Route{from_id: bor.id, to_id: gen.id, distance: 1520})
Repo.insert!(%Route{from_id: bor.id, to_id: nap.id, distance: 1695})
Repo.insert!(%Route{from_id: bor.id, to_id: lvo.id, distance: 1514})
Repo.insert!(%Route{from_id: bor.id, to_id: anc.id, distance: 1538})
Repo.insert!(%Route{from_id: bor.id, to_id: val.id, distance: 1985})
Repo.insert!(%Route{from_id: bor.id, to_id: con.id, distance: 2664})
Repo.insert!(%Route{from_id: bor.id, to_id: smi.id, distance: 2285})
Repo.insert!(%Route{from_id: bor.id, to_id: sal.id, distance: 2084})
Repo.insert!(%Route{from_id: bor.id, to_id: cph.id, distance: 1131})
Repo.insert!(%Route{from_id: bor.id, to_id: sto.id, distance: 1594})
Repo.insert!(%Route{from_id: bor.id, to_id: ber.id, distance: 1119})
Repo.insert!(%Route{from_id: bor.id, to_id: ham.id, distance: 1107})
Repo.insert!(%Route{from_id: bor.id, to_id: lub.id, distance: 1107})
Repo.insert!(%Route{from_id: bor.id, to_id: bre.id, distance: 1026})
Repo.insert!(%Route{from_id: bor.id, to_id: gdn.id, distance: 1339})
Repo.insert!(%Route{from_id: bor.id, to_id: arg.id, distance: 5292})
Repo.insert!(%Route{from_id: mrs.id, to_id: lon.id, distance: 376})
Repo.insert!(%Route{from_id: mrs.id, to_id: brs.id, distance: 489})
Repo.insert!(%Route{from_id: mrs.id, to_id: ply.id, distance: 579})
Repo.insert!(%Route{from_id: mrs.id, to_id: liv.id, distance: 569})
Repo.insert!(%Route{from_id: mrs.id, to_id: edi.id, distance: 736})
Repo.insert!(%Route{from_id: mrs.id, to_id: gla.id, distance: 700})
Repo.insert!(%Route{from_id: mrs.id, to_id: dub.id, distance: 782})
Repo.insert!(%Route{from_id: mrs.id, to_id: ams.id, distance: 542})
Repo.insert!(%Route{from_id: mrs.id, to_id: rot.id, distance: 542})
Repo.insert!(%Route{from_id: mrs.id, to_id: mid.id, distance: 490})
Repo.insert!(%Route{from_id: mrs.id, to_id: ant.id, distance: 309})
Repo.insert!(%Route{from_id: mrs.id, to_id: rou.id, distance: 279})
Repo.insert!(%Route{from_id: mrs.id, to_id: lro.id, distance: 270})
Repo.insert!(%Route{from_id: mrs.id, to_id: bor.id, distance: 394})
Repo.insert!(%Route{from_id: mrs.id, to_id: sev.id, distance: 607})
Repo.insert!(%Route{from_id: mrs.id, to_id: cad.id, distance: 607})
Repo.insert!(%Route{from_id: mrs.id, to_id: bar.id, distance: 216})
Repo.insert!(%Route{from_id: mrs.id, to_id: lis.id, distance: 825})
Repo.insert!(%Route{from_id: mrs.id, to_id: por.id, distance: 825})
Repo.insert!(%Route{from_id: mrs.id, to_id: ven.id, distance: 1212})
Repo.insert!(%Route{from_id: mrs.id, to_id: gen.id, distance: 1303})
Repo.insert!(%Route{from_id: mrs.id, to_id: nap.id, distance: 1478})
Repo.insert!(%Route{from_id: mrs.id, to_id: lvo.id, distance: 1298})
Repo.insert!(%Route{from_id: mrs.id, to_id: anc.id, distance: 1321})
Repo.insert!(%Route{from_id: mrs.id, to_id: val.id, distance: 1768})
Repo.insert!(%Route{from_id: mrs.id, to_id: con.id, distance: 2447})
Repo.insert!(%Route{from_id: mrs.id, to_id: smi.id, distance: 2068})
Repo.insert!(%Route{from_id: mrs.id, to_id: sal.id, distance: 1867})
Repo.insert!(%Route{from_id: mrs.id, to_id: cph.id, distance: 914})
Repo.insert!(%Route{from_id: mrs.id, to_id: sto.id, distance: 1377})
Repo.insert!(%Route{from_id: mrs.id, to_id: ber.id, distance: 1081})
Repo.insert!(%Route{from_id: mrs.id, to_id: ham.id, distance: 948})
Repo.insert!(%Route{from_id: mrs.id, to_id: lub.id, distance: 948})
Repo.insert!(%Route{from_id: mrs.id, to_id: bre.id, distance: 956})
Repo.insert!(%Route{from_id: mrs.id, to_id: gdn.id, distance: 1122})
Repo.insert!(%Route{from_id: mrs.id, to_id: arg.id, distance: 5075})
Repo.insert!(%Route{from_id: sev.id, to_id: lon.id, distance: 870})
Repo.insert!(%Route{from_id: sev.id, to_id: brs.id, distance: 983})
Repo.insert!(%Route{from_id: sev.id, to_id: ply.id, distance: 930})
Repo.insert!(%Route{from_id: sev.id, to_id: liv.id, distance: 1064})
Repo.insert!(%Route{from_id: sev.id, to_id: edi.id, distance: 1177})
Repo.insert!(%Route{from_id: sev.id, to_id: gla.id, distance: 1082})
Repo.insert!(%Route{from_id: sev.id, to_id: dub.id, distance: 903})
Repo.insert!(%Route{from_id: sev.id, to_id: ams.id, distance: 1036})
Repo.insert!(%Route{from_id: sev.id, to_id: rot.id, distance: 1036})
Repo.insert!(%Route{from_id: sev.id, to_id: mid.id, distance: 985})
Repo.insert!(%Route{from_id: sev.id, to_id: ant.id, distance: 916})
Repo.insert!(%Route{from_id: sev.id, to_id: rou.id, distance: 773})
Repo.insert!(%Route{from_id: sev.id, to_id: lro.id, distance: 580})
Repo.insert!(%Route{from_id: sev.id, to_id: bor.id, distance: 456})
Repo.insert!(%Route{from_id: sev.id, to_id: mrs.id, distance: 607})
Repo.insert!(%Route{from_id: sev.id, to_id: bar.id, distance: 390})
Repo.insert!(%Route{from_id: sev.id, to_id: lis.id, distance: 218})
Repo.insert!(%Route{from_id: sev.id, to_id: por.id, distance: 218})
Repo.insert!(%Route{from_id: sev.id, to_id: ven.id, distance: 1819})
Repo.insert!(%Route{from_id: sev.id, to_id: gen.id, distance: 1910})
Repo.insert!(%Route{from_id: sev.id, to_id: nap.id, distance: 2085})
Repo.insert!(%Route{from_id: sev.id, to_id: lvo.id, distance: 1905})
Repo.insert!(%Route{from_id: sev.id, to_id: anc.id, distance: 1928})
Repo.insert!(%Route{from_id: sev.id, to_id: val.id, distance: 2376})
Repo.insert!(%Route{from_id: sev.id, to_id: con.id, distance: 3054})
Repo.insert!(%Route{from_id: sev.id, to_id: smi.id, distance: 2675})
Repo.insert!(%Route{from_id: sev.id, to_id: sal.id, distance: 2474})
Repo.insert!(%Route{from_id: sev.id, to_id: cph.id, distance: 1521})
Repo.insert!(%Route{from_id: sev.id, to_id: sto.id, distance: 1984})
Repo.insert!(%Route{from_id: sev.id, to_id: ber.id, distance: 1575})
Repo.insert!(%Route{from_id: sev.id, to_id: ham.id, distance: 1555})
Repo.insert!(%Route{from_id: sev.id, to_id: lub.id, distance: 1555})
Repo.insert!(%Route{from_id: sev.id, to_id: bre.id, distance: 1482})
Repo.insert!(%Route{from_id: sev.id, to_id: gdn.id, distance: 1729})
Repo.insert!(%Route{from_id: sev.id, to_id: arg.id, distance: 5682})
Repo.insert!(%Route{from_id: cad.id, to_id: lon.id, distance: 870})
Repo.insert!(%Route{from_id: cad.id, to_id: brs.id, distance: 983})
Repo.insert!(%Route{from_id: cad.id, to_id: ply.id, distance: 930})
Repo.insert!(%Route{from_id: cad.id, to_id: liv.id, distance: 1064})
Repo.insert!(%Route{from_id: cad.id, to_id: edi.id, distance: 1177})
Repo.insert!(%Route{from_id: cad.id, to_id: gla.id, distance: 1082})
Repo.insert!(%Route{from_id: cad.id, to_id: dub.id, distance: 903})
Repo.insert!(%Route{from_id: cad.id, to_id: ams.id, distance: 1036})
Repo.insert!(%Route{from_id: cad.id, to_id: rot.id, distance: 1036})
Repo.insert!(%Route{from_id: cad.id, to_id: mid.id, distance: 985})
Repo.insert!(%Route{from_id: cad.id, to_id: ant.id, distance: 916})
Repo.insert!(%Route{from_id: cad.id, to_id: rou.id, distance: 773})
Repo.insert!(%Route{from_id: cad.id, to_id: lro.id, distance: 580})
Repo.insert!(%Route{from_id: cad.id, to_id: bor.id, distance: 456})
Repo.insert!(%Route{from_id: cad.id, to_id: mrs.id, distance: 607})
Repo.insert!(%Route{from_id: cad.id, to_id: bar.id, distance: 390})
Repo.insert!(%Route{from_id: cad.id, to_id: lis.id, distance: 218})
Repo.insert!(%Route{from_id: cad.id, to_id: por.id, distance: 218})
Repo.insert!(%Route{from_id: cad.id, to_id: ven.id, distance: 1819})
Repo.insert!(%Route{from_id: cad.id, to_id: gen.id, distance: 1910})
Repo.insert!(%Route{from_id: cad.id, to_id: nap.id, distance: 2085})
Repo.insert!(%Route{from_id: cad.id, to_id: lvo.id, distance: 1905})
Repo.insert!(%Route{from_id: cad.id, to_id: anc.id, distance: 1928})
Repo.insert!(%Route{from_id: cad.id, to_id: val.id, distance: 2376})
Repo.insert!(%Route{from_id: cad.id, to_id: con.id, distance: 3054})
Repo.insert!(%Route{from_id: cad.id, to_id: smi.id, distance: 2675})
Repo.insert!(%Route{from_id: cad.id, to_id: sal.id, distance: 2474})
Repo.insert!(%Route{from_id: cad.id, to_id: cph.id, distance: 1521})
Repo.insert!(%Route{from_id: cad.id, to_id: sto.id, distance: 1984})
Repo.insert!(%Route{from_id: cad.id, to_id: ber.id, distance: 1575})
Repo.insert!(%Route{from_id: cad.id, to_id: ham.id, distance: 1555})
Repo.insert!(%Route{from_id: cad.id, to_id: lub.id, distance: 1555})
Repo.insert!(%Route{from_id: cad.id, to_id: bre.id, distance: 1482})
Repo.insert!(%Route{from_id: cad.id, to_id: gdn.id, distance: 1729})
Repo.insert!(%Route{from_id: cad.id, to_id: arg.id, distance: 5682})
Repo.insert!(%Route{from_id: bar.id, to_id: lon.id, distance: 592})
Repo.insert!(%Route{from_id: bar.id, to_id: brs.id, distance: 706})
Repo.insert!(%Route{from_id: bar.id, to_id: ply.id, distance: 795})
Repo.insert!(%Route{from_id: bar.id, to_id: liv.id, distance: 786})
Repo.insert!(%Route{from_id: bar.id, to_id: edi.id, distance: 953})
Repo.insert!(%Route{from_id: bar.id, to_id: gla.id, distance: 916})
Repo.insert!(%Route{from_id: bar.id, to_id: dub.id, distance: 999})
Repo.insert!(%Route{from_id: bar.id, to_id: ams.id, distance: 758})
Repo.insert!(%Route{from_id: bar.id, to_id: rot.id, distance: 758})
Repo.insert!(%Route{from_id: bar.id, to_id: mid.id, distance: 707})
Repo.insert!(%Route{from_id: bar.id, to_id: ant.id, distance: 526})
Repo.insert!(%Route{from_id: bar.id, to_id: rou.id, distance: 495})
Repo.insert!(%Route{from_id: bar.id, to_id: lro.id, distance: 486})
Repo.insert!(%Route{from_id: bar.id, to_id: bor.id, distance: 568})
Repo.insert!(%Route{from_id: bar.id, to_id: mrs.id, distance: 216})
Repo.insert!(%Route{from_id: bar.id, to_id: sev.id, distance: 390})
Repo.insert!(%Route{from_id: bar.id, to_id: cad.id, distance: 390})
Repo.insert!(%Route{from_id: bar.id, to_id: lis.id, distance: 608})
Repo.insert!(%Route{from_id: bar.id, to_id: por.id, distance: 608})
Repo.insert!(%Route{from_id: bar.id, to_id: ven.id, distance: 1428})
Repo.insert!(%Route{from_id: bar.id, to_id: gen.id, distance: 1519})
Repo.insert!(%Route{from_id: bar.id, to_id: nap.id, distance: 1695})
Repo.insert!(%Route{from_id: bar.id, to_id: lvo.id, distance: 1514})
Repo.insert!(%Route{from_id: bar.id, to_id: anc.id, distance: 1537})
Repo.insert!(%Route{from_id: bar.id, to_id: val.id, distance: 1985})
Repo.insert!(%Route{from_id: bar.id, to_id: con.id, distance: 2663})
Repo.insert!(%Route{from_id: bar.id, to_id: smi.id, distance: 2284})
Repo.insert!(%Route{from_id: bar.id, to_id: sal.id, distance: 2083})
Repo.insert!(%Route{from_id: bar.id, to_id: cph.id, distance: 1131})
Repo.insert!(%Route{from_id: bar.id, to_id: sto.id, distance: 1593})
Repo.insert!(%Route{from_id: bar.id, to_id: ber.id, distance: 1297})
Repo.insert!(%Route{from_id: bar.id, to_id: ham.id, distance: 1165})
Repo.insert!(%Route{from_id: bar.id, to_id: lub.id, distance: 1165})
Repo.insert!(%Route{from_id: bar.id, to_id: bre.id, distance: 1172})
Repo.insert!(%Route{from_id: bar.id, to_id: gdn.id, distance: 1339})
Repo.insert!(%Route{from_id: bar.id, to_id: arg.id, distance: 5292})
Repo.insert!(%Route{from_id: lis.id, to_id: lon.id, distance: 1085})
Repo.insert!(%Route{from_id: lis.id, to_id: brs.id, distance: 1155})
Repo.insert!(%Route{from_id: lis.id, to_id: ply.id, distance: 898})
Repo.insert!(%Route{from_id: lis.id, to_id: liv.id, distance: 1084})
Repo.insert!(%Route{from_id: lis.id, to_id: edi.id, distance: 1145})
Repo.insert!(%Route{from_id: lis.id, to_id: gla.id, distance: 1050})
Repo.insert!(%Route{from_id: lis.id, to_id: dub.id, distance: 871})
Repo.insert!(%Route{from_id: lis.id, to_id: ams.id, distance: 1254})
Repo.insert!(%Route{from_id: lis.id, to_id: rot.id, distance: 1254})
Repo.insert!(%Route{from_id: lis.id, to_id: mid.id, distance: 1203})
Repo.insert!(%Route{from_id: lis.id, to_id: ant.id, distance: 1135})
Repo.insert!(%Route{from_id: lis.id, to_id: rou.id, distance: 991})
Repo.insert!(%Route{from_id: lis.id, to_id: lro.id, distance: 799})
Repo.insert!(%Route{from_id: lis.id, to_id: bor.id, distance: 674})
Repo.insert!(%Route{from_id: lis.id, to_id: mrs.id, distance: 825})
Repo.insert!(%Route{from_id: lis.id, to_id: sev.id, distance: 218})
Repo.insert!(%Route{from_id: lis.id, to_id: cad.id, distance: 218})
Repo.insert!(%Route{from_id: lis.id, to_id: bar.id, distance: 608})
Repo.insert!(%Route{from_id: lis.id, to_id: ven.id, distance: 2037})
Repo.insert!(%Route{from_id: lis.id, to_id: gen.id, distance: 2128})
Repo.insert!(%Route{from_id: lis.id, to_id: nap.id, distance: 2304})
Repo.insert!(%Route{from_id: lis.id, to_id: lvo.id, distance: 2123})
Repo.insert!(%Route{from_id: lis.id, to_id: anc.id, distance: 2146})
Repo.insert!(%Route{from_id: lis.id, to_id: val.id, distance: 2594})
Repo.insert!(%Route{from_id: lis.id, to_id: con.id, distance: 3272})
Repo.insert!(%Route{from_id: lis.id, to_id: smi.id, distance: 2893})
Repo.insert!(%Route{from_id: lis.id, to_id: sal.id, distance: 2692})
Repo.insert!(%Route{from_id: lis.id, to_id: cph.id, distance: 1739})
Repo.insert!(%Route{from_id: lis.id, to_id: sto.id, distance: 2202})
Repo.insert!(%Route{from_id: lis.id, to_id: ber.id, distance: 1697})
Repo.insert!(%Route{from_id: lis.id, to_id: ham.id, distance: 1774})
Repo.insert!(%Route{from_id: lis.id, to_id: lub.id, distance: 1774})
Repo.insert!(%Route{from_id: lis.id, to_id: bre.id, distance: 1701})
Repo.insert!(%Route{from_id: lis.id, to_id: gdn.id, distance: 1948})
Repo.insert!(%Route{from_id: lis.id, to_id: arg.id, distance: 5901})
Repo.insert!(%Route{from_id: por.id, to_id: lon.id, distance: 1085})
Repo.insert!(%Route{from_id: por.id, to_id: brs.id, distance: 1155})
Repo.insert!(%Route{from_id: por.id, to_id: ply.id, distance: 898})
Repo.insert!(%Route{from_id: por.id, to_id: liv.id, distance: 1084})
Repo.insert!(%Route{from_id: por.id, to_id: edi.id, distance: 1145})
Repo.insert!(%Route{from_id: por.id, to_id: gla.id, distance: 1050})
Repo.insert!(%Route{from_id: por.id, to_id: dub.id, distance: 871})
Repo.insert!(%Route{from_id: por.id, to_id: ams.id, distance: 1254})
Repo.insert!(%Route{from_id: por.id, to_id: rot.id, distance: 1254})
Repo.insert!(%Route{from_id: por.id, to_id: mid.id, distance: 1203})
Repo.insert!(%Route{from_id: por.id, to_id: ant.id, distance: 1135})
Repo.insert!(%Route{from_id: por.id, to_id: rou.id, distance: 991})
Repo.insert!(%Route{from_id: por.id, to_id: lro.id, distance: 799})
Repo.insert!(%Route{from_id: por.id, to_id: bor.id, distance: 674})
Repo.insert!(%Route{from_id: por.id, to_id: mrs.id, distance: 825})
Repo.insert!(%Route{from_id: por.id, to_id: sev.id, distance: 218})
Repo.insert!(%Route{from_id: por.id, to_id: cad.id, distance: 218})
Repo.insert!(%Route{from_id: por.id, to_id: bar.id, distance: 608})
Repo.insert!(%Route{from_id: por.id, to_id: ven.id, distance: 2037})
Repo.insert!(%Route{from_id: por.id, to_id: gen.id, distance: 2128})
Repo.insert!(%Route{from_id: por.id, to_id: nap.id, distance: 2304})
Repo.insert!(%Route{from_id: por.id, to_id: lvo.id, distance: 2123})
Repo.insert!(%Route{from_id: por.id, to_id: anc.id, distance: 2146})
Repo.insert!(%Route{from_id: por.id, to_id: val.id, distance: 2594})
Repo.insert!(%Route{from_id: por.id, to_id: con.id, distance: 3272})
Repo.insert!(%Route{from_id: por.id, to_id: smi.id, distance: 2893})
Repo.insert!(%Route{from_id: por.id, to_id: sal.id, distance: 2692})
Repo.insert!(%Route{from_id: por.id, to_id: cph.id, distance: 1739})
Repo.insert!(%Route{from_id: por.id, to_id: sto.id, distance: 2202})
Repo.insert!(%Route{from_id: por.id, to_id: ber.id, distance: 1697})
Repo.insert!(%Route{from_id: por.id, to_id: ham.id, distance: 1774})
Repo.insert!(%Route{from_id: por.id, to_id: lub.id, distance: 1774})
Repo.insert!(%Route{from_id: por.id, to_id: bre.id, distance: 1701})
Repo.insert!(%Route{from_id: por.id, to_id: gdn.id, distance: 1948})
Repo.insert!(%Route{from_id: por.id, to_id: arg.id, distance: 5901})
Repo.insert!(%Route{from_id: ven.id, to_id: lon.id, distance: 1202})
Repo.insert!(%Route{from_id: ven.id, to_id: brs.id, distance: 1400})
Repo.insert!(%Route{from_id: ven.id, to_id: ply.id, distance: 1504})
Repo.insert!(%Route{from_id: ven.id, to_id: liv.id, distance: 1360})
Repo.insert!(%Route{from_id: ven.id, to_id: edi.id, distance: 1518})
Repo.insert!(%Route{from_id: ven.id, to_id: gla.id, distance: 1491})
Repo.insert!(%Route{from_id: ven.id, to_id: dub.id, distance: 1573})
Repo.insert!(%Route{from_id: ven.id, to_id: ams.id, distance: 981})
Repo.insert!(%Route{from_id: ven.id, to_id: rot.id, distance: 981})
Repo.insert!(%Route{from_id: ven.id, to_id: mid.id, distance: 1032})
Repo.insert!(%Route{from_id: ven.id, to_id: ant.id, distance: 902})
Repo.insert!(%Route{from_id: ven.id, to_id: rou.id, distance: 1204})
Repo.insert!(%Route{from_id: ven.id, to_id: lro.id, distance: 1304})
Repo.insert!(%Route{from_id: ven.id, to_id: bor.id, distance: 1429})
Repo.insert!(%Route{from_id: ven.id, to_id: mrs.id, distance: 1212})
Repo.insert!(%Route{from_id: ven.id, to_id: sev.id, distance: 1819})
Repo.insert!(%Route{from_id: ven.id, to_id: cad.id, distance: 1819})
Repo.insert!(%Route{from_id: ven.id, to_id: bar.id, distance: 1428})
Repo.insert!(%Route{from_id: ven.id, to_id: lis.id, distance: 2037})
Repo.insert!(%Route{from_id: ven.id, to_id: por.id, distance: 2037})
Repo.insert!(%Route{from_id: ven.id, to_id: gen.id, distance: 90})
Repo.insert!(%Route{from_id: ven.id, to_id: nap.id, distance: 266})
Repo.insert!(%Route{from_id: ven.id, to_id: lvo.id, distance: 85})
Repo.insert!(%Route{from_id: ven.id, to_id: anc.id, distance: 109})
Repo.insert!(%Route{from_id: ven.id, to_id: val.id, distance: 556})
Repo.insert!(%Route{from_id: ven.id, to_id: con.id, distance: 1234})
Repo.insert!(%Route{from_id: ven.id, to_id: smi.id, distance: 855})
Repo.insert!(%Route{from_id: ven.id, to_id: sal.id, distance: 654})
Repo.insert!(%Route{from_id: ven.id, to_id: cph.id, distance: 578})
Repo.insert!(%Route{from_id: ven.id, to_id: sto.id, distance: 948})
Repo.insert!(%Route{from_id: ven.id, to_id: ber.id, distance: 1125})
Repo.insert!(%Route{from_id: ven.id, to_id: ham.id, distance: 677})
Repo.insert!(%Route{from_id: ven.id, to_id: lub.id, distance: 677})
Repo.insert!(%Route{from_id: ven.id, to_id: bre.id, distance: 684})
Repo.insert!(%Route{from_id: ven.id, to_id: gdn.id, distance: 591})
Repo.insert!(%Route{from_id: ven.id, to_id: arg.id, distance: 3863})
Repo.insert!(%Route{from_id: gen.id, to_id: lon.id, distance: 1293})
Repo.insert!(%Route{from_id: gen.id, to_id: brs.id, distance: 1491})
Repo.insert!(%Route{from_id: gen.id, to_id: ply.id, distance: 1595})
Repo.insert!(%Route{from_id: gen.id, to_id: liv.id, distance: 1451})
Repo.insert!(%Route{from_id: gen.id, to_id: edi.id, distance: 1609})
Repo.insert!(%Route{from_id: gen.id, to_id: gla.id, distance: 1582})
Repo.insert!(%Route{from_id: gen.id, to_id: dub.id, distance: 1664})
Repo.insert!(%Route{from_id: gen.id, to_id: ams.id, distance: 1072})
Repo.insert!(%Route{from_id: gen.id, to_id: rot.id, distance: 1072})
Repo.insert!(%Route{from_id: gen.id, to_id: mid.id, distance: 1123})
Repo.insert!(%Route{from_id: gen.id, to_id: ant.id, distance: 993})
Repo.insert!(%Route{from_id: gen.id, to_id: rou.id, distance: 1295})
Repo.insert!(%Route{from_id: gen.id, to_id: lro.id, distance: 1395})
Repo.insert!(%Route{from_id: gen.id, to_id: bor.id, distance: 1520})
Repo.insert!(%Route{from_id: gen.id, to_id: mrs.id, distance: 1303})
Repo.insert!(%Route{from_id: gen.id, to_id: sev.id, distance: 1910})
Repo.insert!(%Route{from_id: gen.id, to_id: cad.id, distance: 1910})
Repo.insert!(%Route{from_id: gen.id, to_id: bar.id, distance: 1519})
Repo.insert!(%Route{from_id: gen.id, to_id: lis.id, distance: 2128})
Repo.insert!(%Route{from_id: gen.id, to_id: por.id, distance: 2128})
Repo.insert!(%Route{from_id: gen.id, to_id: ven.id, distance: 90})
Repo.insert!(%Route{from_id: gen.id, to_id: nap.id, distance: 357})
Repo.insert!(%Route{from_id: gen.id, to_id: lvo.id, distance: 176})
Repo.insert!(%Route{from_id: gen.id, to_id: anc.id, distance: 199})
Repo.insert!(%Route{from_id: gen.id, to_id: val.id, distance: 647})
Repo.insert!(%Route{from_id: gen.id, to_id: con.id, distance: 1325})
Repo.insert!(%Route{from_id: gen.id, to_id: smi.id, distance: 946})
Repo.insert!(%Route{from_id: gen.id, to_id: sal.id, distance: 745})
Repo.insert!(%Route{from_id: gen.id, to_id: cph.id, distance: 669})
Repo.insert!(%Route{from_id: gen.id, to_id: sto.id, distance: 1039})
Repo.insert!(%Route{from_id: gen.id, to_id: ber.id, distance: 1216})
Repo.insert!(%Route{from_id: gen.id, to_id: ham.id, distance: 768})
Repo.insert!(%Route{from_id: gen.id, to_id: lub.id, distance: 768})
Repo.insert!(%Route{from_id: gen.id, to_id: bre.id, distance: 775})
Repo.insert!(%Route{from_id: gen.id, to_id: gdn.id, distance: 682})
Repo.insert!(%Route{from_id: gen.id, to_id: arg.id, distance: 3954})
Repo.insert!(%Route{from_id: nap.id, to_id: lon.id, distance: 1468})
Repo.insert!(%Route{from_id: nap.id, to_id: brs.id, distance: 1667})
Repo.insert!(%Route{from_id: nap.id, to_id: ply.id, distance: 1771})
Repo.insert!(%Route{from_id: nap.id, to_id: liv.id, distance: 1627})
Repo.insert!(%Route{from_id: nap.id, to_id: edi.id, distance: 1784})
Repo.insert!(%Route{from_id: nap.id, to_id: gla.id, distance: 1758})
Repo.insert!(%Route{from_id: nap.id, to_id: dub.id, distance: 1840})
Repo.insert!(%Route{from_id: nap.id, to_id: ams.id, distance: 1248})
Repo.insert!(%Route{from_id: nap.id, to_id: rot.id, distance: 1248})
Repo.insert!(%Route{from_id: nap.id, to_id: mid.id, distance: 1299})
Repo.insert!(%Route{from_id: nap.id, to_id: ant.id, distance: 1168})
Repo.insert!(%Route{from_id: nap.id, to_id: rou.id, distance: 1471})
Repo.insert!(%Route{from_id: nap.id, to_id: lro.id, distance: 1571})
Repo.insert!(%Route{from_id: nap.id, to_id: bor.id, distance: 1695})
Repo.insert!(%Route{from_id: nap.id, to_id: mrs.id, distance: 1478})
Repo.insert!(%Route{from_id: nap.id, to_id: sev.id, distance: 2085})
Repo.insert!(%Route{from_id: nap.id, to_id: cad.id, distance: 2085})
Repo.insert!(%Route{from_id: nap.id, to_id: bar.id, distance: 1695})
Repo.insert!(%Route{from_id: nap.id, to_id: lis.id, distance: 2304})
Repo.insert!(%Route{from_id: nap.id, to_id: por.id, distance: 2304})
Repo.insert!(%Route{from_id: nap.id, to_id: ven.id, distance: 266})
Repo.insert!(%Route{from_id: nap.id, to_id: gen.id, distance: 357})
Repo.insert!(%Route{from_id: nap.id, to_id: lvo.id, distance: 352})
Repo.insert!(%Route{from_id: nap.id, to_id: anc.id, distance: 157})
Repo.insert!(%Route{from_id: nap.id, to_id: val.id, distance: 605})
Repo.insert!(%Route{from_id: nap.id, to_id: con.id, distance: 968})
Repo.insert!(%Route{from_id: nap.id, to_id: smi.id, distance: 589})
Repo.insert!(%Route{from_id: nap.id, to_id: sal.id, distance: 388})
Repo.insert!(%Route{from_id: nap.id, to_id: cph.id, distance: 845})
Repo.insert!(%Route{from_id: nap.id, to_id: sto.id, distance: 1214})
Repo.insert!(%Route{from_id: nap.id, to_id: ber.id, distance: 1392})
Repo.insert!(%Route{from_id: nap.id, to_id: ham.id, distance: 943})
Repo.insert!(%Route{from_id: nap.id, to_id: lub.id, distance: 943})
Repo.insert!(%Route{from_id: nap.id, to_id: bre.id, distance: 951})
Repo.insert!(%Route{from_id: nap.id, to_id: gdn.id, distance: 858})
Repo.insert!(%Route{from_id: nap.id, to_id: arg.id, distance: 3596})
Repo.insert!(%Route{from_id: lvo.id, to_id: lon.id, distance: 1287})
Repo.insert!(%Route{from_id: lvo.id, to_id: brs.id, distance: 1486})
Repo.insert!(%Route{from_id: lvo.id, to_id: ply.id, distance: 1590})
Repo.insert!(%Route{from_id: lvo.id, to_id: liv.id, distance: 1446})
Repo.insert!(%Route{from_id: lvo.id, to_id: edi.id, distance: 1604})
Repo.insert!(%Route{from_id: lvo.id, to_id: gla.id, distance: 1577})
Repo.insert!(%Route{from_id: lvo.id, to_id: dub.id, distance: 1659})
Repo.insert!(%Route{from_id: lvo.id, to_id: ams.id, distance: 1067})
Repo.insert!(%Route{from_id: lvo.id, to_id: rot.id, distance: 1067})
Repo.insert!(%Route{from_id: lvo.id, to_id: mid.id, distance: 1118})
Repo.insert!(%Route{from_id: lvo.id, to_id: ant.id, distance: 988})
Repo.insert!(%Route{from_id: lvo.id, to_id: rou.id, distance: 1290})
Repo.insert!(%Route{from_id: lvo.id, to_id: lro.id, distance: 1390})
Repo.insert!(%Route{from_id: lvo.id, to_id: bor.id, distance: 1514})
Repo.insert!(%Route{from_id: lvo.id, to_id: mrs.id, distance: 1298})
Repo.insert!(%Route{from_id: lvo.id, to_id: sev.id, distance: 1905})
Repo.insert!(%Route{from_id: lvo.id, to_id: cad.id, distance: 1905})
Repo.insert!(%Route{from_id: lvo.id, to_id: bar.id, distance: 1514})
Repo.insert!(%Route{from_id: lvo.id, to_id: lis.id, distance: 2123})
Repo.insert!(%Route{from_id: lvo.id, to_id: por.id, distance: 2123})
Repo.insert!(%Route{from_id: lvo.id, to_id: ven.id, distance: 85})
Repo.insert!(%Route{from_id: lvo.id, to_id: gen.id, distance: 176})
Repo.insert!(%Route{from_id: lvo.id, to_id: nap.id, distance: 352})
Repo.insert!(%Route{from_id: lvo.id, to_id: anc.id, distance: 194})
Repo.insert!(%Route{from_id: lvo.id, to_id: val.id, distance: 642})
Repo.insert!(%Route{from_id: lvo.id, to_id: con.id, distance: 1320})
Repo.insert!(%Route{from_id: lvo.id, to_id: smi.id, distance: 941})
Repo.insert!(%Route{from_id: lvo.id, to_id: sal.id, distance: 740})
Repo.insert!(%Route{from_id: lvo.id, to_id: cph.id, distance: 664})
Repo.insert!(%Route{from_id: lvo.id, to_id: sto.id, distance: 1034})
Repo.insert!(%Route{from_id: lvo.id, to_id: ber.id, distance: 1211})
Repo.insert!(%Route{from_id: lvo.id, to_id: ham.id, distance: 762})
Repo.insert!(%Route{from_id: lvo.id, to_id: lub.id, distance: 762})
Repo.insert!(%Route{from_id: lvo.id, to_id: bre.id, distance: 770})
Repo.insert!(%Route{from_id: lvo.id, to_id: gdn.id, distance: 677})
Repo.insert!(%Route{from_id: lvo.id, to_id: arg.id, distance: 3949})
Repo.insert!(%Route{from_id: anc.id, to_id: lon.id, distance: 1311})
Repo.insert!(%Route{from_id: anc.id, to_id: brs.id, distance: 1509})
Repo.insert!(%Route{from_id: anc.id, to_id: ply.id, distance: 1613})
Repo.insert!(%Route{from_id: anc.id, to_id: liv.id, distance: 1470})
Repo.insert!(%Route{from_id: anc.id, to_id: edi.id, distance: 1627})
Repo.insert!(%Route{from_id: anc.id, to_id: gla.id, distance: 1600})
Repo.insert!(%Route{from_id: anc.id, to_id: dub.id, distance: 1682})
Repo.insert!(%Route{from_id: anc.id, to_id: ams.id, distance: 1090})
Repo.insert!(%Route{from_id: anc.id, to_id: rot.id, distance: 1090})
Repo.insert!(%Route{from_id: anc.id, to_id: mid.id, distance: 1141})
Repo.insert!(%Route{from_id: anc.id, to_id: ant.id, distance: 1011})
Repo.insert!(%Route{from_id: anc.id, to_id: rou.id, distance: 1313})
Repo.insert!(%Route{from_id: anc.id, to_id: lro.id, distance: 1413})
Repo.insert!(%Route{from_id: anc.id, to_id: bor.id, distance: 1538})
Repo.insert!(%Route{from_id: anc.id, to_id: mrs.id, distance: 1321})
Repo.insert!(%Route{from_id: anc.id, to_id: sev.id, distance: 1928})
Repo.insert!(%Route{from_id: anc.id, to_id: cad.id, distance: 1928})
Repo.insert!(%Route{from_id: anc.id, to_id: bar.id, distance: 1537})
Repo.insert!(%Route{from_id: anc.id, to_id: lis.id, distance: 2146})
Repo.insert!(%Route{from_id: anc.id, to_id: por.id, distance: 2146})
Repo.insert!(%Route{from_id: anc.id, to_id: ven.id, distance: 109})
Repo.insert!(%Route{from_id: anc.id, to_id: gen.id, distance: 199})
Repo.insert!(%Route{from_id: anc.id, to_id: nap.id, distance: 157})
Repo.insert!(%Route{from_id: anc.id, to_id: lvo.id, distance: 194})
Repo.insert!(%Route{from_id: anc.id, to_id: val.id, distance: 447})
Repo.insert!(%Route{from_id: anc.id, to_id: con.id, distance: 1125})
Repo.insert!(%Route{from_id: anc.id, to_id: smi.id, distance: 746})
Repo.insert!(%Route{from_id: anc.id, to_id: sal.id, distance: 545})
Repo.insert!(%Route{from_id: anc.id, to_id: cph.id, distance: 687})
Repo.insert!(%Route{from_id: anc.id, to_id: sto.id, distance: 1057})
Repo.insert!(%Route{from_id: anc.id, to_id: ber.id, distance: 1234})
Repo.insert!(%Route{from_id: anc.id, to_id: ham.id, distance: 786})
Repo.insert!(%Route{from_id: anc.id, to_id: lub.id, distance: 786})
Repo.insert!(%Route{from_id: anc.id, to_id: bre.id, distance: 793})
Repo.insert!(%Route{from_id: anc.id, to_id: gdn.id, distance: 701})
Repo.insert!(%Route{from_id: anc.id, to_id: arg.id, distance: 3754})
Repo.insert!(%Route{from_id: val.id, to_id: lon.id, distance: 1758})
Repo.insert!(%Route{from_id: val.id, to_id: brs.id, distance: 1957})
Repo.insert!(%Route{from_id: val.id, to_id: ply.id, distance: 2061})
Repo.insert!(%Route{from_id: val.id, to_id: liv.id, distance: 1917})
Repo.insert!(%Route{from_id: val.id, to_id: edi.id, distance: 2074})
Repo.insert!(%Route{from_id: val.id, to_id: gla.id, distance: 2048})
Repo.insert!(%Route{from_id: val.id, to_id: dub.id, distance: 2130})
Repo.insert!(%Route{from_id: val.id, to_id: ams.id, distance: 1538})
Repo.insert!(%Route{from_id: val.id, to_id: rot.id, distance: 1538})
Repo.insert!(%Route{from_id: val.id, to_id: mid.id, distance: 1589})
Repo.insert!(%Route{from_id: val.id, to_id: ant.id, distance: 1459})
Repo.insert!(%Route{from_id: val.id, to_id: rou.id, distance: 1761})
Repo.insert!(%Route{from_id: val.id, to_id: lro.id, distance: 1861})
Repo.insert!(%Route{from_id: val.id, to_id: bor.id, distance: 1985})
Repo.insert!(%Route{from_id: val.id, to_id: mrs.id, distance: 1768})
Repo.insert!(%Route{from_id: val.id, to_id: sev.id, distance: 2376})
Repo.insert!(%Route{from_id: val.id, to_id: cad.id, distance: 2376})
Repo.insert!(%Route{from_id: val.id, to_id: bar.id, distance: 1985})
Repo.insert!(%Route{from_id: val.id, to_id: lis.id, distance: 2594})
Repo.insert!(%Route{from_id: val.id, to_id: por.id, distance: 2594})
Repo.insert!(%Route{from_id: val.id, to_id: ven.id, distance: 556})
Repo.insert!(%Route{from_id: val.id, to_id: gen.id, distance: 647})
Repo.insert!(%Route{from_id: val.id, to_id: nap.id, distance: 605})
Repo.insert!(%Route{from_id: val.id, to_id: lvo.id, distance: 642})
Repo.insert!(%Route{from_id: val.id, to_id: anc.id, distance: 447})
Repo.insert!(%Route{from_id: val.id, to_id: con.id, distance: 684})
Repo.insert!(%Route{from_id: val.id, to_id: smi.id, distance: 796})
Repo.insert!(%Route{from_id: val.id, to_id: sal.id, distance: 993})
Repo.insert!(%Route{from_id: val.id, to_id: cph.id, distance: 1135})
Repo.insert!(%Route{from_id: val.id, to_id: sto.id, distance: 1505})
Repo.insert!(%Route{from_id: val.id, to_id: ber.id, distance: 1682})
Repo.insert!(%Route{from_id: val.id, to_id: ham.id, distance: 1233})
Repo.insert!(%Route{from_id: val.id, to_id: lub.id, distance: 1233})
Repo.insert!(%Route{from_id: val.id, to_id: bre.id, distance: 1241})
Repo.insert!(%Route{from_id: val.id, to_id: gdn.id, distance: 1148})
Repo.insert!(%Route{from_id: val.id, to_id: arg.id, distance: 3313})
Repo.insert!(%Route{from_id: con.id, to_id: lon.id, distance: 2436})
Repo.insert!(%Route{from_id: con.id, to_id: brs.id, distance: 2635})
Repo.insert!(%Route{from_id: con.id, to_id: ply.id, distance: 2739})
Repo.insert!(%Route{from_id: con.id, to_id: liv.id, distance: 2595})
Repo.insert!(%Route{from_id: con.id, to_id: edi.id, distance: 2753})
Repo.insert!(%Route{from_id: con.id, to_id: gla.id, distance: 2726})
Repo.insert!(%Route{from_id: con.id, to_id: dub.id, distance: 2808})
Repo.insert!(%Route{from_id: con.id, to_id: ams.id, distance: 2216})
Repo.insert!(%Route{from_id: con.id, to_id: rot.id, distance: 2216})
Repo.insert!(%Route{from_id: con.id, to_id: mid.id, distance: 2267})
Repo.insert!(%Route{from_id: con.id, to_id: ant.id, distance: 2137})
Repo.insert!(%Route{from_id: con.id, to_id: rou.id, distance: 2439})
Repo.insert!(%Route{from_id: con.id, to_id: lro.id, distance: 2539})
Repo.insert!(%Route{from_id: con.id, to_id: bor.id, distance: 2664})
Repo.insert!(%Route{from_id: con.id, to_id: mrs.id, distance: 2447})
Repo.insert!(%Route{from_id: con.id, to_id: sev.id, distance: 3054})
Repo.insert!(%Route{from_id: con.id, to_id: cad.id, distance: 3054})
Repo.insert!(%Route{from_id: con.id, to_id: bar.id, distance: 2663})
Repo.insert!(%Route{from_id: con.id, to_id: lis.id, distance: 3272})
Repo.insert!(%Route{from_id: con.id, to_id: por.id, distance: 3272})
Repo.insert!(%Route{from_id: con.id, to_id: ven.id, distance: 1234})
Repo.insert!(%Route{from_id: con.id, to_id: gen.id, distance: 1325})
Repo.insert!(%Route{from_id: con.id, to_id: nap.id, distance: 968})
Repo.insert!(%Route{from_id: con.id, to_id: lvo.id, distance: 1320})
Repo.insert!(%Route{from_id: con.id, to_id: anc.id, distance: 1125})
Repo.insert!(%Route{from_id: con.id, to_id: val.id, distance: 684})
Repo.insert!(%Route{from_id: con.id, to_id: smi.id, distance: 378})
Repo.insert!(%Route{from_id: con.id, to_id: sal.id, distance: 579})
Repo.insert!(%Route{from_id: con.id, to_id: cph.id, distance: 1813})
Repo.insert!(%Route{from_id: con.id, to_id: sto.id, distance: 2183})
Repo.insert!(%Route{from_id: con.id, to_id: ber.id, distance: 2360})
Repo.insert!(%Route{from_id: con.id, to_id: ham.id, distance: 1912})
Repo.insert!(%Route{from_id: con.id, to_id: lub.id, distance: 1912})
Repo.insert!(%Route{from_id: con.id, to_id: bre.id, distance: 1919})
Repo.insert!(%Route{from_id: con.id, to_id: gdn.id, distance: 1826})
Repo.insert!(%Route{from_id: con.id, to_id: arg.id, distance: 2896})
Repo.insert!(%Route{from_id: smi.id, to_id: lon.id, distance: 2058})
Repo.insert!(%Route{from_id: smi.id, to_id: brs.id, distance: 2256})
Repo.insert!(%Route{from_id: smi.id, to_id: ply.id, distance: 2360})
Repo.insert!(%Route{from_id: smi.id, to_id: liv.id, distance: 2216})
Repo.insert!(%Route{from_id: smi.id, to_id: edi.id, distance: 2374})
Repo.insert!(%Route{from_id: smi.id, to_id: gla.id, distance: 2347})
Repo.insert!(%Route{from_id: smi.id, to_id: dub.id, distance: 2429})
Repo.insert!(%Route{from_id: smi.id, to_id: ams.id, distance: 1837})
Repo.insert!(%Route{from_id: smi.id, to_id: rot.id, distance: 1837})
Repo.insert!(%Route{from_id: smi.id, to_id: mid.id, distance: 1888})
Repo.insert!(%Route{from_id: smi.id, to_id: ant.id, distance: 1758})
Repo.insert!(%Route{from_id: smi.id, to_id: rou.id, distance: 2060})
Repo.insert!(%Route{from_id: smi.id, to_id: lro.id, distance: 2160})
Repo.insert!(%Route{from_id: smi.id, to_id: bor.id, distance: 2285})
Repo.insert!(%Route{from_id: smi.id, to_id: mrs.id, distance: 2068})
Repo.insert!(%Route{from_id: smi.id, to_id: sev.id, distance: 2675})
Repo.insert!(%Route{from_id: smi.id, to_id: cad.id, distance: 2675})
Repo.insert!(%Route{from_id: smi.id, to_id: bar.id, distance: 2284})
Repo.insert!(%Route{from_id: smi.id, to_id: lis.id, distance: 2893})
Repo.insert!(%Route{from_id: smi.id, to_id: por.id, distance: 2893})
Repo.insert!(%Route{from_id: smi.id, to_id: ven.id, distance: 855})
Repo.insert!(%Route{from_id: smi.id, to_id: gen.id, distance: 946})
Repo.insert!(%Route{from_id: smi.id, to_id: nap.id, distance: 589})
Repo.insert!(%Route{from_id: smi.id, to_id: lvo.id, distance: 941})
Repo.insert!(%Route{from_id: smi.id, to_id: anc.id, distance: 746})
Repo.insert!(%Route{from_id: smi.id, to_id: val.id, distance: 796})
Repo.insert!(%Route{from_id: smi.id, to_id: con.id, distance: 378})
Repo.insert!(%Route{from_id: smi.id, to_id: sal.id, distance: 201})
Repo.insert!(%Route{from_id: smi.id, to_id: cph.id, distance: 1434})
Repo.insert!(%Route{from_id: smi.id, to_id: sto.id, distance: 1804})
Repo.insert!(%Route{from_id: smi.id, to_id: ber.id, distance: 1981})
Repo.insert!(%Route{from_id: smi.id, to_id: ham.id, distance: 1533})
Repo.insert!(%Route{from_id: smi.id, to_id: lub.id, distance: 1533})
Repo.insert!(%Route{from_id: smi.id, to_id: bre.id, distance: 1540})
Repo.insert!(%Route{from_id: smi.id, to_id: gdn.id, distance: 1447})
Repo.insert!(%Route{from_id: smi.id, to_id: arg.id, distance: 3007})
Repo.insert!(%Route{from_id: sal.id, to_id: lon.id, distance: 1857})
Repo.insert!(%Route{from_id: sal.id, to_id: brs.id, distance: 2055})
Repo.insert!(%Route{from_id: sal.id, to_id: ply.id, distance: 2159})
Repo.insert!(%Route{from_id: sal.id, to_id: liv.id, distance: 2015})
Repo.insert!(%Route{from_id: sal.id, to_id: edi.id, distance: 2173})
Repo.insert!(%Route{from_id: sal.id, to_id: gla.id, distance: 2146})
Repo.insert!(%Route{from_id: sal.id, to_id: dub.id, distance: 2228})
Repo.insert!(%Route{from_id: sal.id, to_id: ams.id, distance: 1636})
Repo.insert!(%Route{from_id: sal.id, to_id: rot.id, distance: 1636})
Repo.insert!(%Route{from_id: sal.id, to_id: mid.id, distance: 1687})
Repo.insert!(%Route{from_id: sal.id, to_id: ant.id, distance: 1557})
Repo.insert!(%Route{from_id: sal.id, to_id: rou.id, distance: 1859})
Repo.insert!(%Route{from_id: sal.id, to_id: lro.id, distance: 1959})
Repo.insert!(%Route{from_id: sal.id, to_id: bor.id, distance: 2084})
Repo.insert!(%Route{from_id: sal.id, to_id: mrs.id, distance: 1867})
Repo.insert!(%Route{from_id: sal.id, to_id: sev.id, distance: 2474})
Repo.insert!(%Route{from_id: sal.id, to_id: cad.id, distance: 2474})
Repo.insert!(%Route{from_id: sal.id, to_id: bar.id, distance: 2083})
Repo.insert!(%Route{from_id: sal.id, to_id: lis.id, distance: 2692})
Repo.insert!(%Route{from_id: sal.id, to_id: por.id, distance: 2692})
Repo.insert!(%Route{from_id: sal.id, to_id: ven.id, distance: 654})
Repo.insert!(%Route{from_id: sal.id, to_id: gen.id, distance: 745})
Repo.insert!(%Route{from_id: sal.id, to_id: nap.id, distance: 388})
Repo.insert!(%Route{from_id: sal.id, to_id: lvo.id, distance: 740})
Repo.insert!(%Route{from_id: sal.id, to_id: anc.id, distance: 545})
Repo.insert!(%Route{from_id: sal.id, to_id: val.id, distance: 993})
Repo.insert!(%Route{from_id: sal.id, to_id: con.id, distance: 579})
Repo.insert!(%Route{from_id: sal.id, to_id: smi.id, distance: 201})
Repo.insert!(%Route{from_id: sal.id, to_id: cph.id, distance: 1233})
Repo.insert!(%Route{from_id: sal.id, to_id: sto.id, distance: 1603})
Repo.insert!(%Route{from_id: sal.id, to_id: ber.id, distance: 1780})
Repo.insert!(%Route{from_id: sal.id, to_id: ham.id, distance: 1332})
Repo.insert!(%Route{from_id: sal.id, to_id: lub.id, distance: 1332})
Repo.insert!(%Route{from_id: sal.id, to_id: bre.id, distance: 1339})
Repo.insert!(%Route{from_id: sal.id, to_id: gdn.id, distance: 1246})
Repo.insert!(%Route{from_id: sal.id, to_id: arg.id, distance: 3208})
Repo.insert!(%Route{from_id: cph.id, to_id: lon.id, distance: 904})
Repo.insert!(%Route{from_id: cph.id, to_id: brs.id, distance: 1102})
Repo.insert!(%Route{from_id: cph.id, to_id: ply.id, distance: 1207})
Repo.insert!(%Route{from_id: cph.id, to_id: liv.id, distance: 1063})
Repo.insert!(%Route{from_id: cph.id, to_id: edi.id, distance: 1220})
Repo.insert!(%Route{from_id: cph.id, to_id: gla.id, distance: 1193})
Repo.insert!(%Route{from_id: cph.id, to_id: dub.id, distance: 1276})
Repo.insert!(%Route{from_id: cph.id, to_id: ams.id, distance: 683})
Repo.insert!(%Route{from_id: cph.id, to_id: rot.id, distance: 683})
Repo.insert!(%Route{from_id: cph.id, to_id: mid.id, distance: 735})
Repo.insert!(%Route{from_id: cph.id, to_id: ant.id, distance: 604})
Repo.insert!(%Route{from_id: cph.id, to_id: rou.id, distance: 906})
Repo.insert!(%Route{from_id: cph.id, to_id: lro.id, distance: 1006})
Repo.insert!(%Route{from_id: cph.id, to_id: bor.id, distance: 1131})
Repo.insert!(%Route{from_id: cph.id, to_id: mrs.id, distance: 914})
Repo.insert!(%Route{from_id: cph.id, to_id: sev.id, distance: 1521})
Repo.insert!(%Route{from_id: cph.id, to_id: cad.id, distance: 1521})
Repo.insert!(%Route{from_id: cph.id, to_id: bar.id, distance: 1131})
Repo.insert!(%Route{from_id: cph.id, to_id: lis.id, distance: 1739})
Repo.insert!(%Route{from_id: cph.id, to_id: por.id, distance: 1739})
Repo.insert!(%Route{from_id: cph.id, to_id: ven.id, distance: 578})
Repo.insert!(%Route{from_id: cph.id, to_id: gen.id, distance: 669})
Repo.insert!(%Route{from_id: cph.id, to_id: nap.id, distance: 845})
Repo.insert!(%Route{from_id: cph.id, to_id: lvo.id, distance: 664})
Repo.insert!(%Route{from_id: cph.id, to_id: anc.id, distance: 687})
Repo.insert!(%Route{from_id: cph.id, to_id: val.id, distance: 1135})
Repo.insert!(%Route{from_id: cph.id, to_id: con.id, distance: 1813})
Repo.insert!(%Route{from_id: cph.id, to_id: smi.id, distance: 1434})
Repo.insert!(%Route{from_id: cph.id, to_id: sal.id, distance: 1233})
Repo.insert!(%Route{from_id: cph.id, to_id: sto.id, distance: 660})
Repo.insert!(%Route{from_id: cph.id, to_id: ber.id, distance: 678})
Repo.insert!(%Route{from_id: cph.id, to_id: ham.id, distance: 379})
Repo.insert!(%Route{from_id: cph.id, to_id: lub.id, distance: 379})
Repo.insert!(%Route{from_id: cph.id, to_id: bre.id, distance: 386})
Repo.insert!(%Route{from_id: cph.id, to_id: gdn.id, distance: 489})
Repo.insert!(%Route{from_id: cph.id, to_id: arg.id, distance: 4442})
Repo.insert!(%Route{from_id: sto.id, to_id: lon.id, distance: 1367})
Repo.insert!(%Route{from_id: sto.id, to_id: brs.id, distance: 1565})
Repo.insert!(%Route{from_id: sto.id, to_id: ply.id, distance: 1670})
Repo.insert!(%Route{from_id: sto.id, to_id: liv.id, distance: 1526})
Repo.insert!(%Route{from_id: sto.id, to_id: edi.id, distance: 1456})
Repo.insert!(%Route{from_id: sto.id, to_id: gla.id, distance: 1598})
Repo.insert!(%Route{from_id: sto.id, to_id: dub.id, distance: 1729})
Repo.insert!(%Route{from_id: sto.id, to_id: ams.id, distance: 1146})
Repo.insert!(%Route{from_id: sto.id, to_id: rot.id, distance: 1146})
Repo.insert!(%Route{from_id: sto.id, to_id: mid.id, distance: 1198})
Repo.insert!(%Route{from_id: sto.id, to_id: ant.id, distance: 1067})
Repo.insert!(%Route{from_id: sto.id, to_id: rou.id, distance: 1369})
Repo.insert!(%Route{from_id: sto.id, to_id: lro.id, distance: 1469})
Repo.insert!(%Route{from_id: sto.id, to_id: bor.id, distance: 1594})
Repo.insert!(%Route{from_id: sto.id, to_id: mrs.id, distance: 1377})
Repo.insert!(%Route{from_id: sto.id, to_id: sev.id, distance: 1984})
Repo.insert!(%Route{from_id: sto.id, to_id: cad.id, distance: 1984})
Repo.insert!(%Route{from_id: sto.id, to_id: bar.id, distance: 1593})
Repo.insert!(%Route{from_id: sto.id, to_id: lis.id, distance: 2202})
Repo.insert!(%Route{from_id: sto.id, to_id: por.id, distance: 2202})
Repo.insert!(%Route{from_id: sto.id, to_id: ven.id, distance: 948})
Repo.insert!(%Route{from_id: sto.id, to_id: gen.id, distance: 1039})
Repo.insert!(%Route{from_id: sto.id, to_id: nap.id, distance: 1214})
Repo.insert!(%Route{from_id: sto.id, to_id: lvo.id, distance: 1034})
Repo.insert!(%Route{from_id: sto.id, to_id: anc.id, distance: 1057})
Repo.insert!(%Route{from_id: sto.id, to_id: val.id, distance: 1505})
Repo.insert!(%Route{from_id: sto.id, to_id: con.id, distance: 2183})
Repo.insert!(%Route{from_id: sto.id, to_id: smi.id, distance: 1804})
Repo.insert!(%Route{from_id: sto.id, to_id: sal.id, distance: 1603})
Repo.insert!(%Route{from_id: sto.id, to_id: cph.id, distance: 660})
Repo.insert!(%Route{from_id: sto.id, to_id: ber.id, distance: 903})
Repo.insert!(%Route{from_id: sto.id, to_id: ham.id, distance: 842})
Repo.insert!(%Route{from_id: sto.id, to_id: lub.id, distance: 842})
Repo.insert!(%Route{from_id: sto.id, to_id: bre.id, distance: 849})
Repo.insert!(%Route{from_id: sto.id, to_id: gdn.id, distance: 356})
Repo.insert!(%Route{from_id: sto.id, to_id: arg.id, distance: 4811})
Repo.insert!(%Route{from_id: ber.id, to_id: lon.id, distance: 704})
Repo.insert!(%Route{from_id: ber.id, to_id: brs.id, distance: 799})
Repo.insert!(%Route{from_id: ber.id, to_id: ply.id, distance: 1039})
Repo.insert!(%Route{from_id: ber.id, to_id: liv.id, distance: 719})
Repo.insert!(%Route{from_id: ber.id, to_id: edi.id, distance: 552})
Repo.insert!(%Route{from_id: ber.id, to_id: gla.id, distance: 694})
Repo.insert!(%Route{from_id: ber.id, to_id: dub.id, distance: 826})
Repo.insert!(%Route{from_id: ber.id, to_id: ams.id, distance: 609})
Repo.insert!(%Route{from_id: ber.id, to_id: rot.id, distance: 609})
Repo.insert!(%Route{from_id: ber.id, to_id: mid.id, distance: 660})
Repo.insert!(%Route{from_id: ber.id, to_id: ant.id, distance: 1087})
Repo.insert!(%Route{from_id: ber.id, to_id: rou.id, distance: 802})
Repo.insert!(%Route{from_id: ber.id, to_id: lro.id, distance: 994})
Repo.insert!(%Route{from_id: ber.id, to_id: bor.id, distance: 1119})
Repo.insert!(%Route{from_id: ber.id, to_id: mrs.id, distance: 1081})
Repo.insert!(%Route{from_id: ber.id, to_id: sev.id, distance: 1575})
Repo.insert!(%Route{from_id: ber.id, to_id: cad.id, distance: 1575})
Repo.insert!(%Route{from_id: ber.id, to_id: bar.id, distance: 1297})
Repo.insert!(%Route{from_id: ber.id, to_id: lis.id, distance: 1697})
Repo.insert!(%Route{from_id: ber.id, to_id: por.id, distance: 1697})
Repo.insert!(%Route{from_id: ber.id, to_id: ven.id, distance: 1125})
Repo.insert!(%Route{from_id: ber.id, to_id: gen.id, distance: 1216})
Repo.insert!(%Route{from_id: ber.id, to_id: nap.id, distance: 1392})
Repo.insert!(%Route{from_id: ber.id, to_id: lvo.id, distance: 1211})
Repo.insert!(%Route{from_id: ber.id, to_id: anc.id, distance: 1234})
Repo.insert!(%Route{from_id: ber.id, to_id: val.id, distance: 1682})
Repo.insert!(%Route{from_id: ber.id, to_id: con.id, distance: 2360})
Repo.insert!(%Route{from_id: ber.id, to_id: smi.id, distance: 1981})
Repo.insert!(%Route{from_id: ber.id, to_id: sal.id, distance: 1780})
Repo.insert!(%Route{from_id: ber.id, to_id: cph.id, distance: 678})
Repo.insert!(%Route{from_id: ber.id, to_id: sto.id, distance: 903})
Repo.insert!(%Route{from_id: ber.id, to_id: ham.id, distance: 448})
Repo.insert!(%Route{from_id: ber.id, to_id: lub.id, distance: 448})
Repo.insert!(%Route{from_id: ber.id, to_id: bre.id, distance: 530})
Repo.insert!(%Route{from_id: ber.id, to_id: gdn.id, distance: 1036})
Repo.insert!(%Route{from_id: ber.id, to_id: arg.id, distance: 4989})
Repo.insert!(%Route{from_id: ham.id, to_id: lon.id, distance: 740})
Repo.insert!(%Route{from_id: ham.id, to_id: brs.id, distance: 939})
Repo.insert!(%Route{from_id: ham.id, to_id: ply.id, distance: 1075})
Repo.insert!(%Route{from_id: ham.id, to_id: liv.id, distance: 899})
Repo.insert!(%Route{from_id: ham.id, to_id: edi.id, distance: 914})
Repo.insert!(%Route{from_id: ham.id, to_id: gla.id, distance: 1030})
Repo.insert!(%Route{from_id: ham.id, to_id: dub.id, distance: 1112})
Repo.insert!(%Route{from_id: ham.id, to_id: ams.id, distance: 527})
Repo.insert!(%Route{from_id: ham.id, to_id: rot.id, distance: 527})
Repo.insert!(%Route{from_id: ham.id, to_id: mid.id, distance: 578})
Repo.insert!(%Route{from_id: ham.id, to_id: ant.id, distance: 638})
Repo.insert!(%Route{from_id: ham.id, to_id: rou.id, distance: 790})
Repo.insert!(%Route{from_id: ham.id, to_id: lro.id, distance: 982})
Repo.insert!(%Route{from_id: ham.id, to_id: bor.id, distance: 1107})
Repo.insert!(%Route{from_id: ham.id, to_id: mrs.id, distance: 948})
Repo.insert!(%Route{from_id: ham.id, to_id: sev.id, distance: 1555})
Repo.insert!(%Route{from_id: ham.id, to_id: cad.id, distance: 1555})
Repo.insert!(%Route{from_id: ham.id, to_id: bar.id, distance: 1165})
Repo.insert!(%Route{from_id: ham.id, to_id: lis.id, distance: 1774})
Repo.insert!(%Route{from_id: ham.id, to_id: por.id, distance: 1774})
Repo.insert!(%Route{from_id: ham.id, to_id: ven.id, distance: 677})
Repo.insert!(%Route{from_id: ham.id, to_id: gen.id, distance: 768})
Repo.insert!(%Route{from_id: ham.id, to_id: nap.id, distance: 943})
Repo.insert!(%Route{from_id: ham.id, to_id: lvo.id, distance: 762})
Repo.insert!(%Route{from_id: ham.id, to_id: anc.id, distance: 786})
Repo.insert!(%Route{from_id: ham.id, to_id: val.id, distance: 1233})
Repo.insert!(%Route{from_id: ham.id, to_id: con.id, distance: 1912})
Repo.insert!(%Route{from_id: ham.id, to_id: smi.id, distance: 1533})
Repo.insert!(%Route{from_id: ham.id, to_id: sal.id, distance: 1332})
Repo.insert!(%Route{from_id: ham.id, to_id: cph.id, distance: 379})
Repo.insert!(%Route{from_id: ham.id, to_id: sto.id, distance: 842})
Repo.insert!(%Route{from_id: ham.id, to_id: ber.id, distance: 448})
Repo.insert!(%Route{from_id: ham.id, to_id: bre.id, distance: 421})
Repo.insert!(%Route{from_id: ham.id, to_id: gdn.id, distance: 587})
Repo.insert!(%Route{from_id: ham.id, to_id: arg.id, distance: 4540})
Repo.insert!(%Route{from_id: lub.id, to_id: lon.id, distance: 740})
Repo.insert!(%Route{from_id: lub.id, to_id: brs.id, distance: 939})
Repo.insert!(%Route{from_id: lub.id, to_id: ply.id, distance: 1075})
Repo.insert!(%Route{from_id: lub.id, to_id: liv.id, distance: 899})
Repo.insert!(%Route{from_id: lub.id, to_id: edi.id, distance: 914})
Repo.insert!(%Route{from_id: lub.id, to_id: gla.id, distance: 1030})
Repo.insert!(%Route{from_id: lub.id, to_id: dub.id, distance: 1112})
Repo.insert!(%Route{from_id: lub.id, to_id: ams.id, distance: 527})
Repo.insert!(%Route{from_id: lub.id, to_id: rot.id, distance: 527})
Repo.insert!(%Route{from_id: lub.id, to_id: mid.id, distance: 578})
Repo.insert!(%Route{from_id: lub.id, to_id: ant.id, distance: 638})
Repo.insert!(%Route{from_id: lub.id, to_id: rou.id, distance: 790})
Repo.insert!(%Route{from_id: lub.id, to_id: lro.id, distance: 982})
Repo.insert!(%Route{from_id: lub.id, to_id: bor.id, distance: 1107})
Repo.insert!(%Route{from_id: lub.id, to_id: mrs.id, distance: 948})
Repo.insert!(%Route{from_id: lub.id, to_id: sev.id, distance: 1555})
Repo.insert!(%Route{from_id: lub.id, to_id: cad.id, distance: 1555})
Repo.insert!(%Route{from_id: lub.id, to_id: bar.id, distance: 1165})
Repo.insert!(%Route{from_id: lub.id, to_id: lis.id, distance: 1774})
Repo.insert!(%Route{from_id: lub.id, to_id: por.id, distance: 1774})
Repo.insert!(%Route{from_id: lub.id, to_id: ven.id, distance: 677})
Repo.insert!(%Route{from_id: lub.id, to_id: gen.id, distance: 768})
Repo.insert!(%Route{from_id: lub.id, to_id: nap.id, distance: 943})
Repo.insert!(%Route{from_id: lub.id, to_id: lvo.id, distance: 762})
Repo.insert!(%Route{from_id: lub.id, to_id: anc.id, distance: 786})
Repo.insert!(%Route{from_id: lub.id, to_id: val.id, distance: 1233})
Repo.insert!(%Route{from_id: lub.id, to_id: con.id, distance: 1912})
Repo.insert!(%Route{from_id: lub.id, to_id: smi.id, distance: 1533})
Repo.insert!(%Route{from_id: lub.id, to_id: sal.id, distance: 1332})
Repo.insert!(%Route{from_id: lub.id, to_id: cph.id, distance: 379})
Repo.insert!(%Route{from_id: lub.id, to_id: sto.id, distance: 842})
Repo.insert!(%Route{from_id: lub.id, to_id: ber.id, distance: 448})
Repo.insert!(%Route{from_id: lub.id, to_id: bre.id, distance: 421})
Repo.insert!(%Route{from_id: lub.id, to_id: gdn.id, distance: 587})
Repo.insert!(%Route{from_id: lub.id, to_id: arg.id, distance: 4540})
Repo.insert!(%Route{from_id: bre.id, to_id: lon.id, distance: 659})
Repo.insert!(%Route{from_id: bre.id, to_id: brs.id, distance: 858})
Repo.insert!(%Route{from_id: bre.id, to_id: ply.id, distance: 994})
Repo.insert!(%Route{from_id: bre.id, to_id: liv.id, distance: 818})
Repo.insert!(%Route{from_id: bre.id, to_id: edi.id, distance: 833})
Repo.insert!(%Route{from_id: bre.id, to_id: gla.id, distance: 949})
Repo.insert!(%Route{from_id: bre.id, to_id: dub.id, distance: 1031})
Repo.insert!(%Route{from_id: bre.id, to_id: ams.id, distance: 446})
Repo.insert!(%Route{from_id: bre.id, to_id: rot.id, distance: 446})
Repo.insert!(%Route{from_id: bre.id, to_id: mid.id, distance: 497})
Repo.insert!(%Route{from_id: bre.id, to_id: ant.id, distance: 646})
Repo.insert!(%Route{from_id: bre.id, to_id: rou.id, distance: 709})
Repo.insert!(%Route{from_id: bre.id, to_id: lro.id, distance: 902})
Repo.insert!(%Route{from_id: bre.id, to_id: bor.id, distance: 1026})
Repo.insert!(%Route{from_id: bre.id, to_id: mrs.id, distance: 956})
Repo.insert!(%Route{from_id: bre.id, to_id: sev.id, distance: 1482})
Repo.insert!(%Route{from_id: bre.id, to_id: cad.id, distance: 1482})
Repo.insert!(%Route{from_id: bre.id, to_id: bar.id, distance: 1172})
Repo.insert!(%Route{from_id: bre.id, to_id: lis.id, distance: 1701})
Repo.insert!(%Route{from_id: bre.id, to_id: por.id, distance: 1701})
Repo.insert!(%Route{from_id: bre.id, to_id: ven.id, distance: 684})
Repo.insert!(%Route{from_id: bre.id, to_id: gen.id, distance: 775})
Repo.insert!(%Route{from_id: bre.id, to_id: nap.id, distance: 951})
Repo.insert!(%Route{from_id: bre.id, to_id: lvo.id, distance: 770})
Repo.insert!(%Route{from_id: bre.id, to_id: anc.id, distance: 793})
Repo.insert!(%Route{from_id: bre.id, to_id: val.id, distance: 1241})
Repo.insert!(%Route{from_id: bre.id, to_id: con.id, distance: 1919})
Repo.insert!(%Route{from_id: bre.id, to_id: smi.id, distance: 1540})
Repo.insert!(%Route{from_id: bre.id, to_id: sal.id, distance: 1339})
Repo.insert!(%Route{from_id: bre.id, to_id: cph.id, distance: 386})
Repo.insert!(%Route{from_id: bre.id, to_id: sto.id, distance: 849})
Repo.insert!(%Route{from_id: bre.id, to_id: ber.id, distance: 530})
Repo.insert!(%Route{from_id: bre.id, to_id: ham.id, distance: 421})
Repo.insert!(%Route{from_id: bre.id, to_id: lub.id, distance: 421})
Repo.insert!(%Route{from_id: bre.id, to_id: gdn.id, distance: 594})
Repo.insert!(%Route{from_id: bre.id, to_id: arg.id, distance: 4548})
Repo.insert!(%Route{from_id: gdn.id, to_id: lon.id, distance: 1112})
Repo.insert!(%Route{from_id: gdn.id, to_id: brs.id, distance: 1311})
Repo.insert!(%Route{from_id: gdn.id, to_id: ply.id, distance: 1415})
Repo.insert!(%Route{from_id: gdn.id, to_id: liv.id, distance: 1271})
Repo.insert!(%Route{from_id: gdn.id, to_id: edi.id, distance: 1428})
Repo.insert!(%Route{from_id: gdn.id, to_id: gla.id, distance: 1402})
Repo.insert!(%Route{from_id: gdn.id, to_id: dub.id, distance: 1484})
Repo.insert!(%Route{from_id: gdn.id, to_id: ams.id, distance: 892})
Repo.insert!(%Route{from_id: gdn.id, to_id: rot.id, distance: 892})
Repo.insert!(%Route{from_id: gdn.id, to_id: mid.id, distance: 943})
Repo.insert!(%Route{from_id: gdn.id, to_id: ant.id, distance: 812})
Repo.insert!(%Route{from_id: gdn.id, to_id: rou.id, distance: 1115})
Repo.insert!(%Route{from_id: gdn.id, to_id: lro.id, distance: 1215})
Repo.insert!(%Route{from_id: gdn.id, to_id: bor.id, distance: 1339})
Repo.insert!(%Route{from_id: gdn.id, to_id: mrs.id, distance: 1122})
Repo.insert!(%Route{from_id: gdn.id, to_id: sev.id, distance: 1729})
Repo.insert!(%Route{from_id: gdn.id, to_id: cad.id, distance: 1729})
Repo.insert!(%Route{from_id: gdn.id, to_id: bar.id, distance: 1339})
Repo.insert!(%Route{from_id: gdn.id, to_id: lis.id, distance: 1948})
Repo.insert!(%Route{from_id: gdn.id, to_id: por.id, distance: 1948})
Repo.insert!(%Route{from_id: gdn.id, to_id: ven.id, distance: 591})
Repo.insert!(%Route{from_id: gdn.id, to_id: gen.id, distance: 682})
Repo.insert!(%Route{from_id: gdn.id, to_id: nap.id, distance: 858})
Repo.insert!(%Route{from_id: gdn.id, to_id: lvo.id, distance: 677})
Repo.insert!(%Route{from_id: gdn.id, to_id: anc.id, distance: 701})
Repo.insert!(%Route{from_id: gdn.id, to_id: val.id, distance: 1148})
Repo.insert!(%Route{from_id: gdn.id, to_id: con.id, distance: 1826})
Repo.insert!(%Route{from_id: gdn.id, to_id: smi.id, distance: 1447})
Repo.insert!(%Route{from_id: gdn.id, to_id: sal.id, distance: 1246})
Repo.insert!(%Route{from_id: gdn.id, to_id: cph.id, distance: 489})
Repo.insert!(%Route{from_id: gdn.id, to_id: sto.id, distance: 356})
Repo.insert!(%Route{from_id: gdn.id, to_id: ber.id, distance: 1036})
Repo.insert!(%Route{from_id: gdn.id, to_id: ham.id, distance: 587})
Repo.insert!(%Route{from_id: gdn.id, to_id: lub.id, distance: 587})
Repo.insert!(%Route{from_id: gdn.id, to_id: bre.id, distance: 594})
Repo.insert!(%Route{from_id: gdn.id, to_id: arg.id, distance: 4455})
Repo.insert!(%Route{from_id: arg.id, to_id: lon.id, distance: 5065})
Repo.insert!(%Route{from_id: arg.id, to_id: brs.id, distance: 5264})
Repo.insert!(%Route{from_id: arg.id, to_id: ply.id, distance: 5368})
Repo.insert!(%Route{from_id: arg.id, to_id: liv.id, distance: 5224})
Repo.insert!(%Route{from_id: arg.id, to_id: edi.id, distance: 5381})
Repo.insert!(%Route{from_id: arg.id, to_id: gla.id, distance: 5355})
Repo.insert!(%Route{from_id: arg.id, to_id: dub.id, distance: 5437})
Repo.insert!(%Route{from_id: arg.id, to_id: ams.id, distance: 4845})
Repo.insert!(%Route{from_id: arg.id, to_id: rot.id, distance: 4845})
Repo.insert!(%Route{from_id: arg.id, to_id: mid.id, distance: 4896})
Repo.insert!(%Route{from_id: arg.id, to_id: ant.id, distance: 4765})
Repo.insert!(%Route{from_id: arg.id, to_id: rou.id, distance: 5068})
Repo.insert!(%Route{from_id: arg.id, to_id: lro.id, distance: 5168})
Repo.insert!(%Route{from_id: arg.id, to_id: bor.id, distance: 5292})
Repo.insert!(%Route{from_id: arg.id, to_id: mrs.id, distance: 5075})
Repo.insert!(%Route{from_id: arg.id, to_id: sev.id, distance: 5682})
Repo.insert!(%Route{from_id: arg.id, to_id: cad.id, distance: 5682})
Repo.insert!(%Route{from_id: arg.id, to_id: bar.id, distance: 5292})
Repo.insert!(%Route{from_id: arg.id, to_id: lis.id, distance: 5901})
Repo.insert!(%Route{from_id: arg.id, to_id: por.id, distance: 5901})
Repo.insert!(%Route{from_id: arg.id, to_id: ven.id, distance: 3863})
Repo.insert!(%Route{from_id: arg.id, to_id: gen.id, distance: 3954})
Repo.insert!(%Route{from_id: arg.id, to_id: nap.id, distance: 3596})
Repo.insert!(%Route{from_id: arg.id, to_id: lvo.id, distance: 3949})
Repo.insert!(%Route{from_id: arg.id, to_id: anc.id, distance: 3754})
Repo.insert!(%Route{from_id: arg.id, to_id: val.id, distance: 3313})
Repo.insert!(%Route{from_id: arg.id, to_id: con.id, distance: 2896})
Repo.insert!(%Route{from_id: arg.id, to_id: smi.id, distance: 3007})
Repo.insert!(%Route{from_id: arg.id, to_id: sal.id, distance: 3208})
Repo.insert!(%Route{from_id: arg.id, to_id: cph.id, distance: 4442})
Repo.insert!(%Route{from_id: arg.id, to_id: sto.id, distance: 4811})
Repo.insert!(%Route{from_id: arg.id, to_id: ber.id, distance: 4989})
Repo.insert!(%Route{from_id: arg.id, to_id: ham.id, distance: 4540})
Repo.insert!(%Route{from_id: arg.id, to_id: lub.id, distance: 4540})
Repo.insert!(%Route{from_id: arg.id, to_id: bre.id, distance: 4548})
Repo.insert!(%Route{from_id: arg.id, to_id: gdn.id, distance: 4455})
